(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[sin[c_.+d_.*x_],x_Symbol] :=
  -Cos[c+d*x]/d /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[Sqrt[sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  2*EllipticE[(c+d*x)/2,2]/d /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]],x_Symbol] :=
  -2*EllipticE[Pi/4-(c+d*x)/2,2]/d /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_,x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m-1)/(d*(Sin[c+d*x]^2)^((m-1)/2))*Hypergeometric2F1[(1-m)/2,1/2,3/2,Cos[c+d*x]^2] /;
FreeQ[{c,d,m},x] && RationalQ[m] && 0<m<1 && m!=1/2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_,x_Symbol] :=
  -1/d*Subst[Int[Expand[(1-x^2)^((m-1)/2),x],x],x,Cos[c+d*x]] /;
FreeQ[{c,d},x] && RationalQ[m] && m>1 && OddQ[m]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2,x_Symbol] :=
  x/2 - Cos[c+d*x]*Sin[c+d*x]/(2*d) /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_,x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m-1)/(d*m) + 
  (m-1)/m*Int[Sin[c+d*x]^(m-2),x] /;
FreeQ[{c,d},x] && RationalQ[m] && m>1 && Not[OddQ[m]] && m!=2


(* ::Code:: *)
Int[1/Sqrt[sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  2*EllipticF[(c+d*x)/2,2]/d /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[1/Sqrt[sin[c_.+d_.*x_]],x_Symbol] :=
  -2*EllipticF[Pi/4-(c+d*x)/2,2]/d /;
FreeQ[{c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_,x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(Sin[c+d*x]^2)^((m+1)/2))*Hypergeometric2F1[(1-m)/2,1/2,3/2,Cos[c+d*x]^2] /;
FreeQ[{c,d,m},x] && (Not[RationalQ[m]] || -1<m<0)


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_,x_Symbol] :=
  Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(m+1)) + 
  (m+2)/(m+1)*Int[Sin[c+d*x]^(m+2),x] /;
FreeQ[{c,d},x] && RationalQ[m] && m<-1


(* ::Code:: *)
Int[Sqrt[b_*sin[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[b*Sin[c+d*x]]/Sqrt[Sin[c+d*x]]*Int[Sqrt[Sin[c+d*x]],x] /;
FreeQ[{b,c,d},x]


(* ::Code:: *)
Int[(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b*(b*Sin[c+d*x])^(n-1)/Sin[c+d*x]^(n-1)*Int[Sin[c+d*x]^n,x] /;
FreeQ[{b,c,d},x] && RationalQ[n] && 0<n<1 && n!=1/2


(* ::Code:: *)
Int[(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b*Cos[c+d*x]*(b*Sin[c+d*x])^(n-1)/(d*n) + 
  (b^2*(n-1))/n*Int[(b*Sin[c+d*x])^(n-2),x] /;
FreeQ[{b,c,d},x] && RationalQ[n] && n>1


(* ::Code:: *)
Int[1/Sqrt[b_*sin[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[Sin[c+d*x]]/Sqrt[b*Sin[c+d*x]]*Int[1/Sqrt[Sin[c+d*x]],x] /;
FreeQ[{b,c,d},x]


(* ::Code:: *)
Int[(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  (b*Sin[c+d*x])^(n+1)/(b*Sin[c+d*x]^(n+1))*Int[Sin[c+d*x]^n,x] /;
FreeQ[{b,c,d,n},x] && (Not[RationalQ[n]] || -1<n<0)


(* ::Code:: *)
Int[(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  Cos[c+d*x]*(b*Sin[c+d*x])^(n+1)/(b*d*(n+1)) + 
  (n+2)/(b^2*(n+1))*Int[(b*Sin[c+d*x])^(n+2),x] /;
FreeQ[{b,c,d},x] && RationalQ[n] && n<-1


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*b*Cos[c+d*x]/(d*Sqrt[a+b*Sin[c+d*x]]) /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  2*Sqrt[a+b]/d*EllipticE[(c+d*x)/2,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Sqrt[a+b]/d*EllipticE[Pi/4-(c+d*x)/2,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[a+b*Sin[c+d*x]]/Sqrt[(a+b*Sin[c+d*x])/(a+b)]*Int[Sqrt[a/(a+b)+b/(a+b)*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^2,x_Symbol] :=
  (2*a^2+b^2)*x/2 - b^2*Cos[c+d*x]*Sin[c+d*x]/(2*d) + 2*a*b*Int[Sin[c+d*x],x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n-1)/(d*n) +
  a*(2*n-1)/n*Int[(a+b*Sin[c+d*x])^(n-1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n>1 && n!=2 && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n-1)/(d*n) + 
  1/n*Int[Simp[a^2*n+b^2*(n-1)+a*b*(2*n-1)*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^(n-2),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n>1 && n!=2 && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  -Cos[c+d*x]/(d*(b+a*Sin[c+d*x])) /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  x/Rt[a^2-b^2,2] + 
  2/(d*Rt[a^2-b^2,2])*ArcTan[b*Cos[c+d*x]/(a+Rt[a^2-b^2,2]+b*Sin[c + d*x])] /;
FreeQ[{a,b,c,d},x] && PositiveQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+Pi/2+d_.*x_]),x_Symbol] :=
  2*ArcTan[(a-b)*Tan[(c+d*x)/2]/Rt[a^2-b^2,2]]/(d*Rt[a^2-b^2,2]) /;
FreeQ[{a,b,c,d},x] && PosQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  2*ArcTan[(b+a*Tan[(c+d*x)/2])/Rt[a^2-b^2,2]]/(d*Rt[a^2-b^2,2]) /;
FreeQ[{a,b,c,d},x] && PosQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+Pi/2+d_.*x_]),x_Symbol] :=
  -2*ArcTanh[(a-b)*Tan[(c+d*x)/2]/Rt[b^2-a^2,2]]/(d*Rt[b^2-a^2,2]) /;
FreeQ[{a,b,c,d},x] && NegQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  -2*ArcTanh[(b+a*Tan[(c+d*x)/2])/Rt[b^2-a^2,2]]/(d*Rt[b^2-a^2,2]) /;
FreeQ[{a,b,c,d},x] && NegQ[a^2-b^2]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  2/(d*Sqrt[a+a*Cos[c+d*x]])*Cos[(c+d*x)/2]*ArcTanh[Sin[(c+d*x)/2]] /;
FreeQ[{a,c,d},x] && ZeroQ[a-b]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  -2/(d*Sqrt[a-a*Cos[c+d*x]])*Sin[(c+d*x)/2]*ArcTanh[Cos[(c+d*x)/2]] /;
FreeQ[{a,c,d},x] && ZeroQ[a+b]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  2/(d*Sqrt[a+b*Sin[c+d*x]])*Cos[(c+d*x)/2-Pi*b/(4*a)]*ArcTanh[Sin[(c+d*x)/2-Pi*b/(4*a)]] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]],x_Symbol] :=
  2/(d*Sqrt[a+b])*EllipticF[(c+d*x)/2,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2/(d*Sqrt[a+b])*EllipticF[Pi/4-(c+d*x)/2,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[(a+b*Sin[c+d*x])/(a+b)]/Sqrt[a+b*Sin[c+d*x]]*Int[1/Sqrt[a/(a+b)+b/(a+b)*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b*Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(a*d*(2*n+1)) +
  (n+1)/(a*(2*n+1))*Int[(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + 
  1/((n+1)*(a^2-b^2))*Int[Simp[a*(n+1)-b*(n+2)*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[(a_.+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  Defer[Int][(a+b*Sin[c+d*x])^n,x] /;
FreeQ[{a,b,c,d,n},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_.*(b_.*sin[c_.+d_.*x_])^n_.,x_Symbol] :=
  1/b^m*Int[(b*Sin[c+d*x])^(m+n),x] /;
FreeQ[{b,c,d,n},x] && IntegerQ[m]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b^(n-1/2)*Sqrt[b*Sin[c+d*x]]/Sqrt[Sin[c+d*x]]*Int[Sin[c+d*x]^(m+n),x] /;
FreeQ[{b,c,d},x] && Not[IntegerQ[m]] && PositiveIntegerQ[n+1/2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(b_*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b^(n+1/2)*Sqrt[Sin[c+d*x]]/Sqrt[b*Sin[c+d*x]]*Int[Sin[c+d*x]^(m+n),x] /;
FreeQ[{b,c,d},x] && Not[IntegerQ[m]] && NegativeIntegerQ[n-1/2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_.*(b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  (b*Sin[c+d*x])^n/Sin[c+d*x]^n*Int[Sin[c+d*x]^(m+n),x] /;
FreeQ[{b,c,d,m,n},x] && Not[IntegerQ[m]] && Not[IntegerQ[n-1/2]]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])/sin[c_.+d_.*x_],x_Symbol] :=
  b*x + a*Int[1/Sin[c+d*x],x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_.*(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  a*Int[Sin[c+d*x]^m,x] + b*Int[Sin[c+d*x]^(m+1),x] /;
FreeQ[{a,b,c,d,m},x] && NonzeroQ[m+1]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_.*(a_+b_.*sin[c_.+d_.*x_])^2,x_Symbol] :=
  -b^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(m+2)) + 
  1/(m+2)*Int[Sin[c+d*x]^m*Simp[a^2+(a^2+b^2)*(m+1)+2*a*b*(m+2)*Sin[c+d*x],x],x] /;
FreeQ[{a,b,c,d},x] && RationalQ[m] && m>=-1


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^2,x_Symbol] :=
  a^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(m+1)) + 
  1/(m+1)*Int[Sin[c+d*x]^(m+1)*Simp[2*a*b*(m+1)+(a^2+(a^2+b^2)*(m+1))*Sin[c+d*x],x],x] /;
FreeQ[{a,b,c,d},x] && RationalQ[m] && m<-1


(* ::Code:: *)
Int[sin[c_.+d_.*x_]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(d*(n+1)) + 
  a*n/(b*(n+1))*Int[(a+b*Sin[c+d*x])^n,x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n>0 && n!=2 && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(d*(n+1)) + 
  n/(n+1)*Int[Simp[b+a*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^(n-1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n>0 && n!=2 && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  x/b - a/b*Int[1/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  1/b*Int[Sqrt[a+b*Sin[c+d*x]],x] - 
  a/b*Int[1/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(d*(2*n+1)) + 
  n/(b*(2*n+1))*Int[(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) - 
  1/((n+1)*(a^2-b^2))*Int[Simp[b*(n+1)-a*(n+2)*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^(n+1)/(b*d*(n+2)) + 
  1/(b*(n+2))*Int[Simp[b*(n+1)-a*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^n,x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n>0 && n!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  -Cos[c+d*x]/(b*d) - a/b*Int[Sin[c+d*x]/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Cos[c+d*x]*Sqrt[a+b*Sin[c+d*x]]/(3*b*d) + 
  1/(3*b)*Int[Simp[b-2*a*Sin[c+d*x],x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b*Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(a*d*(2*n+1)) - 
  1/(a^2*(2*n+1))*Int[(a*n-b*(2*n+1)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^2*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -a^2*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + 
  1/(b*(n+1)*(a^2-b^2))*Int[Simp[a*b*(n+1)-(a^2+b^2*(n+1))*Sin[c+d*x],x]*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && RationalQ[n] && n<-1 && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/sin[c_.+d_.*x_]^(3/2),x_Symbol] :=
  -2*a*Cos[c+d*x]/(d*Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]) /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -a*Cos[c+d*x]*(a+b*Sin[c+d*x])^(n-1)/(d*n*Sin[c+d*x]^n) + 
  b*(2*n-1)/n*Int[(a+b*Sin[c+d*x])^(n-1)/Sin[c+d*x]^n,x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && m+n+1==0 && n>1 && n!=2


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+Pi/2+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]]),x_Symbol] :=
  Sqrt[2]/(d*Sqrt[a])*ArcSin[Tan[(c+d*x)/2]] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a-b] && PositiveQ[a]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  Sqrt[2]/(d*Sqrt[a])*ArcSin[Tan[(c+d*x)/2-Pi/4]] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a-b] && PositiveQ[a]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  -Sqrt[2]*Sqrt[b]/(a*d)*ArcTan[Sqrt[b]*Cos[c+d*x]/(Sqrt[2]*Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]])] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && Not[ZeroQ[a-b] && PositiveQ[a]]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a*Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(b*d*(2*n+1)*Sin[c+d*x]^(n+1)) + 
  (n+1)/(b*(2*n+1))*Int[(a+b*Sin[c+d*x])^(n+1)/Sin[c+d*x]^(n+2),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && m+n+1==0 && n<=-1 && m!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(d*(n+1)*Sin[c+d*x]^(n+1)) + 
  a*n/(b*(n+1))*Int[(a+b*Sin[c+d*x])^n/Sin[c+d*x]^(n+1),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && m+n+2==0 && n>-1 && n!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*(a+b*Sin[c+d*x])^n/(d*(2*n+1)*Sin[c+d*x]^(n+1)) + 
  n/(a*(2*n+1))*Int[(a+b*Sin[c+d*x])^(n+1)/Sin[c+d*x]^(n+2),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && m+n+2==0 && n<=-1 && m!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*b*Cos[c+d*x]*Sin[c+d*x]^m/(d*(2*m+1)*Sqrt[a+b*Sin[c+d*x]]) + 
  2*a*m/(b*(2*m+1))*Int[Sin[c+d*x]^(m-1)*Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m] && m>0 && m!=2


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]]/sin[c_.+Pi/2+d_.*x_],x_Symbol] :=
  2*Sqrt[2]*a*Cos[(c+d*x)/2]/(d*Sqrt[a+a*Cos[c+d*x]])*ArcTanh[Sqrt[2]*Sin[(c+d*x)/2]] /;
FreeQ[{a,c,d},x] && ZeroQ[a-b]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]]/sin[c_.+Pi/2+d_.*x_],x_Symbol] :=
  2*Sqrt[2]*a*Sin[(c+d*x)/2]/(d*Sqrt[a-a*Cos[c+d*x]])*ArcTanh[Sqrt[2]*Cos[(c+d*x)/2]] /;
FreeQ[{a,c,d},x] && ZeroQ[a+b]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/sin[c_.+d_.*x_],x_Symbol] :=
  2*Sqrt[2]*b*Cos[(c+d*x)/2-Pi*b/(4*a)]/(d*Sqrt[a+b*Sin[c+d*x]])*ArcTanh[Sqrt[2]*Sin[(c+d*x)/2-Pi*b/(4*a)]] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/Sqrt[sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Sqrt[b]/d*ArcTan[Sqrt[b]*Cos[c+d*x]/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]])] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  a*Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(m+1)*Sqrt[a+b*Sin[c+d*x]]) + 
  b*(2*m+3)/(2*a*(m+1))*Int[Sin[c+d*x]^(m+1)*Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m] && m<=-2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^(n-2)/(d*(m+n)) + 
  a/(m+n)*Int[Sin[c+d*x]^m*(a*(2*m+n+1)+b*(2*m+3*n-2)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n-2),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && n>1 && n!=2 && m>=-1 && m!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^(n-2)/(d*(m+1)) + 
  b/(m+1)*Int[Sin[c+d*x]^(m+1)*(a*(2*m-n+4)+b*(2*m+n+1)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n-2),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && n>1 && n!=2 && m<-1


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  1/b*Int[Sqrt[a+b*Sin[c+d*x]]/Sqrt[Sin[c+d*x]],x] - 
  a/b*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Cos[c+d*x]*Sin[c+d*x]^(m-1)/(d*(2*m-1)*Sqrt[a+b*Sin[c+d*x]]) + 
  1/(b*(2*m-1))*Int[(Sin[c+d*x]^(m-2)*(2*b*(m-1)-a*Sin[c+d*x]))/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m] && m>1 && m!=2


(* ::Code:: *)
Int[1/(sin[c_.+d_.*x_]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  1/a*Int[Sqrt[a+b*Sin[c+d*x]]/Sin[c+d*x],x] - 
  b/a*Int[1/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  Cos[c+d*x]*Sin[c+d*x]^(m+1)/(d*(m+1)*Sqrt[a+b*Sin[c+d*x]]) + 
  1/(2*b*(m+1))*Int[(Sin[c+d*x]^(m+1)*(a+b*(2*m+3)*Sin[c+d*x]))/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m] && m<-1


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a*Cos[c+d*x]*Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^n/(b*d*(2*n+1)) - 
  1/(2*a*b*(2*n+1))*Int[(a-b*(2*n+3)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n+1)/Sqrt[Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[n] && n<=-1


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m-1)*(a+b*Sin[c+d*x])^n/(d*(2*n+1)) + 
  1/(a^2*(2*n+1))*Int[Sin[c+d*x]^(m-2)*(a*(m-1)-b*(m-n-1)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && n<=-1 && m>1 && m!=2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^n/(d*(2*n+1)) + 
  1/(a^2*(2*n+1))*Int[Sin[c+d*x]^m*(a*(m+2*n+2)-b*(m+n+2)*Sin[c+d*x])*(a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && ZeroQ[a^2-b^2] && RationalQ[m,n] && n<=-1 && m<0


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -a*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  Int[(a+a*Sin[c+d*x]+b*Sin[c+d*x]^2)/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Cos[c+d*x]*Sin[c+d*x]^(m-1)*Sqrt[a+b*Sin[c+d*x]]/(d*(2*m+1)) + 
  1/(2*m+1)*Int[Sin[c+d*x]^(m-2)*Simp[2*a*(m-1)+b*(2*m-1)*Sin[c+d*x]+a*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m>1 && m!=2 && IntegerQ[2*m]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/sin[c_.+d_.*x_],x_Symbol] :=
  b*Int[1/Sqrt[a+b*Sin[c+d*x]],x] + 
  a*Int[1/(Sin[c+d*x]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/Sqrt[sin[c_.+d_.*x_]],x_Symbol] :=
  (a-b)*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] +
  b*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*sin[c_.+d_.*x_]]/sin[c_.+d_.*x_]^(3/2),x_Symbol] :=
  (a+b)*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  a*Int[(1-Sin[c+d*x])/(Sin[c+d*x]^(3/2)*Sqrt[a+b*Sin[c+d*x]]),x] /; 
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  Cos[c+d*x]*Sin[c+d*x]^(m+1)*Sqrt[a+b*Sin[c+d*x]]/(d*(m+1)) + 
  1/(2*(m+1))*Int[Sin[c+d*x]^(m+1)*Simp[-b+2*a*(m+1+1)*Sin[c+d*x]+b*(2*m+5)*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m<=-2 && IntegerQ[2*m]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^(3/2),x_Symbol] :=
  -2*b*Cos[c+d*x]*Sin[c+d*x]^m*Sqrt[a+b*Sin[c+d*x]]/(d*(2*m+3)) + 
  1/(2*m+3)*Int[Sin[c+d*x]^(m-1)*Simp[2*a*b*m+((a^2+b^2)*(2*m+3)-2*b^2)*Sin[c+d*x]+2*a*b*(m+2)*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m>0 && m!=2 && IntegerQ[2*m]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^(3/2)/sin[c_.+d_.*x_],x_Symbol] :=
  b*Int[Sqrt[a+b*Sin[c+d*x]],x] + a*Int[Sqrt[a+b*Sin[c+d*x]]/Sin[c+d*x],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^(3/2)/Sqrt[sin[c_.+d_.*x_]],x_Symbol] :=
  3*a*b/2*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  1/2*Int[(a*(2*a-3*b)+a*b*Sin[c+d*x]+2*b^2*Sin[c+d*x]^2)/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[(a_+b_.*sin[c_.+d_.*x_])^(3/2)/sin[c_.+d_.*x_]^(3/2),x_Symbol] :=
  b^2*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  Int[(a^2+b*(2*a-b)*Sin[c+d*x])/(Sin[c+d*x]^(3/2)*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^(3/2),x_Symbol] :=
  a*Cos[c+d*x]*Sin[c+d*x]^(m+1)*Sqrt[a+b*Sin[c+d*x]]/(d*(m+1)) + 
  1/(2*(m+1))*Int[Sin[c+d*x]^(m+1)*Simp[a*b*(2*m+1)+2*(a^2+(a^2+b^2)*(m+1))*Sin[c+d*x]+a*b*(2*m+5)*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m<=-2 && IntegerQ[2*m]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^(n-2)/(d*(m+n)) + 
  1/(m+n)*
    Int[Sin[c+d*x]^m*
      Simp[a*(a^2*(n-1)+(a^2+b^2)*(m+1))+b*(-b^2+(3*a^2+b^2)*(m+n))*Sin[c+d*x]+a*b^2*(2*m+3*n+-2)*Sin[c+d*x]^2,x]*
      (a+b*Sin[c+d*x])^(n-3),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m,n] && n>2 && m>=-1 && m!=2 && IntegersQ[2*m,2*n]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^(n-2)/(d*(m+1)) + 
  1/(m+1)*
    Int[Sin[c+d*x]^(m+1)*
      Simp[a^2*b*(2*m-n+4)+a*(a^2+(a^2+3*b^2)*(m+1))*Sin[c+d*x]+b*(a^2*(n-1)+(a^2+b^2)*(m+1))*Sin[c+d*x]^2,x]*
      (a+b*Sin[c+d*x])^(n-3),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m,n] && n>2 && m<-1 && IntegersQ[2*m,2*n]


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  1/b*Int[1/Sqrt[Sin[c+d*x]],x] - 
  a/b*Int[1/(Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^(3/2)/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  1/b*Int[Sqrt[Sin[c+d*x]],x] - 
  a/b*Int[Sqrt[Sin[c+d*x]]/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  -Cos[c+d*x]*Sin[c+d*x]^(m-2*1)/(b*d*(m-1)) + 
  1/(b*(m-1))*Int[Sin[c+d*x]^(m-3)*Simp[a*(m-2)+b*(m-2)*Sin[c+d*x]-a*(m-1)*Sin[c+d*x]^2,x]/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m>2 && IntegerQ[2*m]


(* ::Code:: *)
Int[1/(sin[c_.+d_.*x_]*(a_+b_.*sin[c_.+d_.*x_])),x_Symbol] :=
  1/a*Int[1/Sin[c+d*x],x] - b/a*Int[1/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+Pi/2+d_.*x_]]*(a_+b_.*sin[c_.+Pi/2+d_.*x_])),x_Symbol] :=
  2/(d*(a+b))*EllipticPi[2*b/(a+b),(c+d*x)/2,2] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*(a_+b_.*sin[c_.+d_.*x_])),x_Symbol] :=
  2/(d*(a+b))*EllipticPi[2*b/(a+b),(c+d*x)/2-Pi/4,2] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/(a_+b_.*sin[c_.+d_.*x_]),x_Symbol] :=
  Cos[c+d*x]*Sin[c+d*x]^(m+1)/(a*d*(m+1)) + 
  1/(a*(m+1))*Int[Sin[c+d*x]^(m+1)*Simp[-b*(m+1)+a*(m+2)*Sin[c+d*x]+b*(m+2)*Sin[c+d*x]^2,x]/(a+b*Sin[c+d*x]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m<-1 && IntegerQ[2*m]


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] +
  Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^(3/2)/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -a/(2*b)*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  1/(2*b)*Int[(a+a*Sin[c+d*x]+2*b*Sin[c+d*x]^2)/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  -2*Cos[c+d*x]*Sin[c+d*x]^(m-2)*Sqrt[a+b*Sin[c+d*x]]/(b*d*(2*m-1)) + 
  1/(b*(2*m-1))*Int[Sin[c+d*x]^(m-3)*Simp[2*a*(m-2)+b*(2*m-3)*Sin[c+d*x]-2*a*(m-1)*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m>2 && IntegerQ[2*m]


(* ::Code:: *)
Int[1/(sin[c_.+Pi/2+d_.*x_]*Sqrt[a_+b_.*sin[c_.+Pi/2+d_.*x_]]),x_Symbol] :=
  2/(d*Rt[a+b,2])*EllipticPi[2,(c+d*x)/2,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[1/(sin[c_.+d_.*x_]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  2/(d*Rt[a+b,2])*EllipticPi[2,(c+d*x)/2-Pi/4,2*b/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[1/(sin[c_.+d_.*x_]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  Sqrt[(a+b*Sin[c+d*x])/(a+b)]/Sqrt[a+b*Sin[c+d*x]]*Int[1/(Sin[c+d*x]*Sqrt[a/(a+b)+b/(a+b)*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  -2/(d*Sqrt[a+b])*EllipticF[ArcSin[Cos[c+d*x]/(1+Sin[c+d*x])],-(a-b)/(a+b)] /;
FreeQ[{a,b,c,d},x] && PositiveQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  -2*Sqrt[1+Sin[c+d*x]]/(d*Sqrt[a+b*Sin[c+d*x]])*
    Sqrt[(a+b*Sin[c+d*x])/((a+b)*(1+Sin[c+d*x]))]*
    EllipticF[ArcSin[Cos[c+d*x]/(1+Sin[c+d*x])],-(a-b)/(a+b)] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(sin[c_.+d_.*x_]^(3/2)*Sqrt[a_+b_.*sin[c_.+d_.*x_]]),x_Symbol] :=
  Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  Int[(1-Sin[c+d*x])/(Sin[c+d*x]^(3/2)*Sqrt[a+b*Sin[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_/Sqrt[a_+b_.*sin[c_.+d_.*x_]],x_Symbol] :=
  Cos[c+d*x]*Sin[c+d*x]^(m+1)*Sqrt[a+b*Sin[c+d*x]]/(a*d*(m+1)) + 
  1/(2*a*(m+1))*Int[Sin[c+d*x]^(m+1)*Simp[-b*(2*m+3)+2*a*(m+2)*Sin[c+d*x]+b*(2*m+5)*Sin[c+d*x]^2,x]/Sqrt[a+b*Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m<=-2 && IntegerQ[2*m]


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]/(a_+b_.*sin[c_.+d_.*x_])^(3/2),x_Symbol] :=
  -1/(a-b)*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] + 
  a/(a-b)*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^(3/2)),x] /; 
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[sin[c_.+d_.*x_]]*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -b*Cos[c+d*x]*Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + 
  1/(2*(n+1)*(a^2-b^2))*Int[Simp[b+2*a*(n+1)*Sin[c+d*x]-b*(2*n+5)*Sin[c+d*x]^2,x]*(a+b*Sin[c+d*x])^(n+1)/Sqrt[Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && IntegersQ[2*n] && n<=-2


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^(3/2)/(a_+b_.*sin[c_.+d_.*x_])^(3/2),x_Symbol] :=
  1/b*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] - 
  1/b*Int[(a+(a+b)*Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^(3/2)),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^(3/2)*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  a*Cos[c+d*x]*Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) - 
  1/(2*(n+1)*(a^2-b^2))*Int[Simp[a+2*b*(n+1)*Sin[c+d*x]-a*(2*n+5)*Sin[c+d*x]^2,x]*(a+b*Sin[c+d*x])^(n+1)/Sqrt[Sin[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[n] && n<=-2 && IntegersQ[2*n]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  -a^2*Cos[c+d*x]*Sin[c+d*x]^(m-2*1)*(a+b*Sin[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + 
  1/(b*(n+1)*(a^2-b^2))*
    Int[Sin[c+d*x]^(m-3*1)*
      Simp[a^2*(m-2)+a*b*(n+1)*Sin[c+d*x]-(b^2*(n+1)+a^2*(m-1))*Sin[c+d*x]^2,x]*
      (a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m,n] && n<-1 && m>2 && IntegersQ[2*m,2*n]


(* ::Code:: *)
Int[1/(Sqrt[sin[c_.+d_.*x_]]*(a_+b_.*sin[c_.+d_.*x_])^(3/2)),x_Symbol] :=
  1/(a-b)*Int[1/(Sqrt[Sin[c+d*x]]*Sqrt[a+b*Sin[c+d*x]]),x] - 
  b/(a-b)*Int[(1+Sin[c+d*x])/(Sqrt[Sin[c+d*x]]*(a+b*Sin[c+d*x])^(3/2)),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_*(a_+b_.*sin[c_.+d_.*x_])^n_,x_Symbol] :=
  b^2*Cos[c+d*x]*Sin[c+d*x]^(m+1)*(a+b*Sin[c+d*x])^(n+1)/(a*d*(n+1)*(a^2-b^2)) + 
  1/(a*(n+1)*(a^2-b^2))*
    Int[Sin[c+d*x]^m*
      Simp[(a^2-b^2)*(n+1)-b^2*(m+1)-a*b*(n+1)*Sin[c+d*x]+b^2*(m+n+3)*Sin[c+d*x]^2,x]*
      (a+b*Sin[c+d*x])^(n+1),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m,n] && n<-1 && m<0 && IntegersQ[2*m,2*n]


(* ::Code:: *)
Int[sin[c_.+d_.*x_]^m_.*(a_.+b_.*sin[c_.+d_.*x_])^n_.,x_Symbol] :=
  Defer[Int][Sin[c+d*x]^m*(a+b*Sin[c+d*x])^n,x] /;
FreeQ[{a,b,c,d,m,n},x]


(* ::Code:: *)
Int[csc[c_.+d_.*x_]^m_*sin[c_.+d_.*x_]^q_.,x_Symbol] :=
  Csc[c+d*x]^m*Sin[c+d*x]^m*Int[Sin[c+d*x]^(q-m),x] /;
FreeQ[{c,d,m,q},x] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[csc[c_.+d_.*x_]^m_*(a_.+b_.*sin[c_.+d_.*x_])^n_.,x_Symbol] :=
  Csc[c+d*x]^m*Sin[c+d*x]^m*Int[(a+b*Sin[c+d*x])^n/Sin[c+d*x]^m,x] /;
FreeQ[{a,b,c,d,m,n},x] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[csc[c_.+d_.*x_]^m_*sin[c_.+d_.*x_]^q_.*(a_.+b_.*sin[c_.+d_.*x_])^n_.,x_Symbol] :=
  Csc[c+d*x]^m*Sin[c+d*x]^m*Int[Sin[c+d*x]^(q-m)*(a+b*Sin[c+d*x])^n,x] /;
FreeQ[{a,b,c,d,m,n,q},x] && Not[IntegerQ[m]]



