<?php
$page_title = 'About Web REDUCE';
$header_title = 'About Web REDUCE';
include '../include/begin-head.php';
include '../include/begin-body.php';
?>
  <h2>Purpose</h2>
  <p>Web REDUCE runs as an app in your web browser and does not need
      any installation. It is intended primarily as a demonstration of
      REDUCE appropriate for simple interactive experimentation. It is
      not intended for heavy-duty problem solving (although you can
      use it however you want).</p>
  <h2>Limitations</h2>
  <p>
      Web REDUCE will be a little slower than conventional REDUCE and
      there may occasionally be a noticeable pause while the REDUCE
      engine downloads. It does not support the standard REDUCE file
      access commands
      <a href="/manual-lookup.php?File%20Handling%20Commands"><code>in</code>, <code>out</code>
      or <code>shut</code></a>. Nor does it support compiling or
      loading user modules or packages. It does, however, provide all
      the standard REDUCE packages, which either autoload as usual or
      can be loaded explicitly with the
      <a href="/manual-lookup.php?User%20Contributed%20Packages"><code>load_package</code></a>
      command.</p>
  <p>
      However, a lot of JavaScript runs asynchronously, which means
      that a single REDUCE input of the form</p>
  <pre><code>statementA; statementB;</code></pre>
  <p><strong>may</strong> not execute <code>statementA</code> before <code>statementB</code>.
      Therefore, it is not advisable to include more than one
      statement in the same input.  This <strong>may</strong> only be
      a problem when <code>statementA</code> involves <code>load_package</code>.
      For example, the single input</p>
  <pre><code>load_package trigd; atan2d(y,x);</code></pre>
  <p>does not work, but it works as two separate inputs.</p>
  <p>
      Web REDUCE does not provide any input prompts, unlike
      conventional REDUCE. This limits the usefulness of the standard
      REDUCE commands <a href="/manual-lookup.php?Referencing%20Previous%20Results"><code>ws</code>
      and <code>input</code></a>, which work but you have to count
      inputs yourself! In principle, the standard REDUCE command
      <a href="/manual-lookup.php?Referencing%20Previous%20Results"><code>display</code></a>
      should help, but it doesn't work.  User queries do not work, so
      Web REDUCE sets <code><a href="/manual-lookup.php?Interactive%20File%20Control">off
      int</a></code> by default. Some of these limitations may get
      removed at some future date.</p>
  <p>
      Web REDUCE cannot run any external programs, so facilities that
      rely on this do not work, in particular plotting.
  <p>
    You need a recent web browser to run Web REDUCE, preferably the
    latest version. It may not run on mobile devices.</p>
  <h2>What is it?</h2>
  <p>
    Web REDUCE consists of a graphical user interface (GUI)
    implemented using HTML, CSS and JavaScript that runs a Wasm
    (<a href="https://webassembly.org/">WebAssembly</a>) version of
    the REDUCE engine by Arthur Norman and Avery Laird, which is CSL
    REDUCE compiled to WebAssembly using <a href="https://emscripten.org/">Emscripten</a>. See
      <a href="https://sourceforge.net/p/reduce-algebra/code/HEAD/tree/trunk/csl/new-embedded/for-emscripten/">SourceForge</a>
    for details of how to build this version of REDUCE, which consists
    of two files, <code>reduce.web.js</code>
    and <code>reduce.web.wasm</code>. The web worker interface to the
    Wasm REDUCE engine uses code developed by Arthur Norman and Avery
    Laird. The Web REDUCE GUI is modelled on
    the <a href="https://fjwright.github.io/Run-REDUCE/">Run-REDUCE</a>
    GUI for conventional REDUCE, which itself is loosely based on the
    CSL REDUCE GUI by Arthur Norman.</p>
  <p>
    Typeset mathematics is output using LaTeX syntax generated by the
    REDUCE <code>tmprint</code> package and rendered by
    the <a href="https://www.mathjax.org/">MathJax</a> JavaScript
    library, which is also used elsewhere on the REDUCE web site.</p>
  <address>Francis Wright, July 2021</address>
</div><!-- opened in begin-body.php -->
<?php include '../include/footer.php'; ?>
</body>
</html>
