#!/bin/bash
# Start the Cygwin, Linux or macOS CCL REDUCE image.
cl=$(realpath $(dirname $0)) # common-lisp directory
if [ "$OSTYPE" == 'cygwin' ]; then cl=$(cygpath -m $cl); fi
if [ "$(type -ft ccl64)" ]; then CCL='ccl64'; else CCL='ccl'; fi
$CCL -I $cl/fasl.ccl/reduce.image
