#!/bin/bash

# Start SBCL REDUCE on Cygwin, Linux or macOS.
# Author: Francis J. Wright <https://sourceforge.net/u/fjwright>
# Time-stamp: <2026-04-06 16:08:40 franc>

for arg do
    case $arg in
        -h|--help)
            echo 'Start SBCL REDUCE on Cygwin, Linux or macOS.'
            echo 'Usage: redsbcl <options>'
            echo 'Useful options:'
            echo '  -h, --help                  Print this message and exit.'
            echo '  --version                   Print SBCL version information and exit.'
            echo '  --control-stack-size <MiB>  Size of reserved control stack; default 2.'
            echo '  --dynamic-space-size <MiB>  Size of reserved dynamic space.'
            echo '  --no-rcfile                 Inhibit REDUCE startup file.'
            exit;;
        --no-rcfile) norcfile='--no-rcfile';;
        *) args="$args $arg";;
    esac
done
args="$args $norcfile"

cl=$(realpath $(dirname $0)) # common-lisp directory
if [ "$OSTYPE" == 'cygwin' ]; then cl=$(cygpath -m $cl); fi
exec sbcl --noinform --core $cl/fasl.sbcl/reduce.img $args

# SBCL runtime options should all work but not SBCL toplevel options,
# which are replaced by REDUCE options.  These are currently only
# --no-rcfile, which must appear after any runtime options.
