#! /bin/csh

#-------------------------------------------------------------
#
#  Compile REDUCE help info into HTML
#
#-------------------------------------------------------------

setenv package redhelp
# if Not "%1" == "" setenv package %1

# setenv tdir html

reduce << EOF

ON ERRCONT;

symbolic;
% !*lower := nil;
on backtrace;
on comp;
!*windows := t;

in "comphelp.red"\$
in "helphtml.red"\$
in "minitex.red"\$

dir_src := "$reduce/doc/help/";
package := getenv "package";

% if package="" or package = "redref"
%   then  << dir_src := "redref\"; package := "redhelp">>
%               else  dir_src := "packages\";

job(bldmsg("%w.tex",package),"null");
<<
terpri();
prin2t "=================================================";
prin2t "  SECOND RUN ";
prin2t "=================================================";
>>;

reset_html();

job(bldmsg("%w.tex",package),"auxx.rtf");

<<
terpri();
prin2t "=================================================";
prin2t "  THIRD RUN ";
prin2t "=================================================";
>>;

reset_html();

job(bldmsg("%w.tex",package),"auxx.rtf");

html_indexfile();
lisp_indexfile();

bye;

EOF
