#! /bin/csh

#-------------------------------------------------------------
#
#  Compile REDUCE help info for Microsoft help compiler format
#
#  After running this script, you need to do, on a PC,
#     hc31 $package
#  assuming the file $package.hpj is there.
#
#-------------------------------------------------------------

set package=redhelp
# if ("$1" != "") set package=$1

reduce <<EOF

ON ERRCONT;

symbolic;
on backtrace;
on comp;
!*windows := t;

in "comphelp.red"\$
in "helpwin.red"\$
in "minitex.red"\$

% TR minitex;
% package := "$1";

%if package="" then  << dir_src := "redref/"; package := "redref">>
%              else  dir_src := "packages/";

dir_src := "$reduce/doc/help/";
package := "redhelp";

job(bldmsg("%w.tex",package),"/dev/null");
<<
terpri();
prin2t "=================================================";
prin2t "  SECOND RUN ";
prin2t "=================================================";
>>;
job(bldmsg("%w.tex",package),"$package.rtf");

%===========================
%
%===========================
% for each s in section_list do print s;

bye;

EOF
