.TH breduce 1 "10 October 2011"
.IX breduce
.SH NAME
breduce - A batch processing facility for REDUCE-
.SH SYNOPSIS
.B breduce
.RI [ configfile ]
.SH DESCRIPTION
breduce takes as input several reduce files
containing input data plus a configuration file. It produces as
output a LaTeX document with the formatted results of all
computations specified in the configuration file. Important features
include the systematic application of all combinations of a choice
of reduce switches and a mechanism for limiting the runtime
of the single computations.
.SH "SEE ALSO"
The documentation can be found in /usr/share/doc/reduce-addons/breduce.pdf.
.SH AUTHOR
Copyright (C) 2008, 2011 T. Sturm
