/* Correctly-rounded base-2 logarithm function for bfloat16 value.

Copyright (c) 2025 Paul Zimmermann

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdint.h>
#include <errno.h>
#include <math.h> // only used during performance tests

// Warning: clang also defines __GNUC__
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#pragma STDC FENV_ACCESS ON

typedef union {__bf16 f; uint16_t u;} b16u16_u;
typedef union {float f; uint32_t u;} b32u32_u;

/* For 0 <= i1 < 2^8, T1[i1] approximates log10(x1), where the 16-bit
   encoding of x1 is i1*2^7 (i1 encodes the exponent of x1).
   Table generated by table1() in log.sage. */
static const float T1[] = {
 0, -0x1.2f703p+5, -0x1.2d07aep+5, -0x1.2a9f2cp+5, -0x1.2836a8p+5,
 -0x1.25ce26p+5, -0x1.2365a4p+5, -0x1.20fd22p+5, -0x1.1e94ap+5,
 -0x1.1c2c1cp+5, -0x1.19c39ap+5, -0x1.175b18p+5, -0x1.14f296p+5,
 -0x1.128a14p+5, -0x1.10219p+5, -0x1.0db90ep+5, -0x1.0b508cp+5,
 -0x1.08e80ap+5, -0x1.067f88p+5, -0x1.041704p+5, -0x1.01ae82p+5, -0x1.fe8cp+4,
 -0x1.f9bafcp+4, -0x1.f4e9f6p+4, -0x1.f018f2p+4, -0x1.eb47ecp+4,
 -0x1.e676e8p+4, -0x1.e1a5e2p+4, -0x1.dcd4dep+4, -0x1.d803dap+4,
 -0x1.d332d4p+4, -0x1.ce61dp+4, -0x1.c990cap+4, -0x1.c4bfc6p+4,
 -0x1.bfeec2p+4, -0x1.bb1dbcp+4, -0x1.b64cb8p+4, -0x1.b17bb2p+4,
 -0x1.acaaaep+4, -0x1.a7d9a8p+4, -0x1.a308a4p+4, -0x1.9e37ap+4,
 -0x1.99669ap+4, -0x1.949596p+4, -0x1.8fc49p+4, -0x1.8af38cp+4,
 -0x1.862288p+4, -0x1.815182p+4, -0x1.7c807ep+4, -0x1.77af78p+4,
 -0x1.72de74p+4, -0x1.6e0d6ep+4, -0x1.693c6ap+4, -0x1.646b66p+4,
 -0x1.5f9a6p+4, -0x1.5ac95cp+4, -0x1.55f856p+4, -0x1.512752p+4,
 -0x1.4c564ep+4, -0x1.478548p+4, -0x1.42b444p+4, -0x1.3de33ep+4,
 -0x1.39123ap+4, -0x1.344136p+4, -0x1.2f703p+4, -0x1.2a9f2cp+4,
 -0x1.25ce26p+4, -0x1.20fd22p+4, -0x1.1c2c1cp+4, -0x1.175b18p+4,
 -0x1.128a14p+4, -0x1.0db90ep+4, -0x1.08e80ap+4, -0x1.041704p+4, -0x1.fe8cp+3,
 -0x1.f4e9f6p+3, -0x1.eb47ecp+3, -0x1.e1a5e2p+3, -0x1.d803dap+3,
 -0x1.ce61dp+3, -0x1.c4bfc6p+3, -0x1.bb1dbcp+3, -0x1.b17bb2p+3,
 -0x1.a7d9a8p+3, -0x1.9e37ap+3, -0x1.949596p+3, -0x1.8af38cp+3,
 -0x1.815182p+3, -0x1.77af78p+3, -0x1.6e0d6ep+3, -0x1.646b66p+3,
 -0x1.5ac95cp+3, -0x1.512752p+3, -0x1.478548p+3, -0x1.3de33ep+3,
 -0x1.344136p+3, -0x1.2a9f2cp+3, -0x1.20fd22p+3, -0x1.175b18p+3,
 -0x1.0db90ep+3, -0x1.041704p+3, -0x1.f4e9f6p+2, -0x1.e1a5e2p+2,
 -0x1.ce61dp+2, -0x1.bb1dbcp+2, -0x1.a7d9a8p+2, -0x1.949596p+2,
 -0x1.815182p+2, -0x1.6e0d6ep+2, -0x1.5ac95cp+2, -0x1.478548p+2,
 -0x1.344136p+2, -0x1.20fd22p+2, -0x1.0db90ep+2, -0x1.f4e9f6p+1,
 -0x1.ce61dp+1, -0x1.a7d9a8p+1, -0x1.815182p+1, -0x1.5ac95cp+1,
 -0x1.344136p+1, -0x1.0db90ep+1, -0x1.ce61dp+0, -0x1.815182p+0,
 -0x1.344136p+0, -0x1.ce61dp-1, -0x1.344136p-1, -0x1.344136p-2, 0x0p+0,
 0x1.344136p-2, 0x1.344136p-1, 0x1.ce61dp-1, 0x1.344136p+0, 0x1.815182p+0,
 0x1.ce61dp+0, 0x1.0db90ep+1, 0x1.344136p+1, 0x1.5ac95cp+1, 0x1.815182p+1,
 0x1.a7d9a8p+1, 0x1.ce61dp+1, 0x1.f4e9f6p+1, 0x1.0db90ep+2, 0x1.20fd22p+2,
 0x1.344136p+2, 0x1.478548p+2, 0x1.5ac95cp+2, 0x1.6e0d6ep+2, 0x1.815182p+2,
 0x1.949596p+2, 0x1.a7d9a8p+2, 0x1.bb1dbcp+2, 0x1.ce61dp+2, 0x1.e1a5e2p+2,
 0x1.f4e9f6p+2, 0x1.041704p+3, 0x1.0db90ep+3, 0x1.175b18p+3, 0x1.20fd22p+3,
 0x1.2a9f2cp+3, 0x1.344136p+3, 0x1.3de33ep+3, 0x1.478548p+3, 0x1.512752p+3,
 0x1.5ac95cp+3, 0x1.646b66p+3, 0x1.6e0d6ep+3, 0x1.77af78p+3, 0x1.815182p+3,
 0x1.8af38cp+3, 0x1.949596p+3, 0x1.9e37ap+3, 0x1.a7d9a8p+3, 0x1.b17bb2p+3,
 0x1.bb1dbcp+3, 0x1.c4bfc6p+3, 0x1.ce61dp+3, 0x1.d803dap+3, 0x1.e1a5e2p+3,
 0x1.eb47ecp+3, 0x1.f4e9f6p+3, 0x1.fe8cp+3, 0x1.041704p+4, 0x1.08e80ap+4,
 0x1.0db90ep+4, 0x1.128a14p+4, 0x1.175b18p+4, 0x1.1c2c1cp+4, 0x1.20fd22p+4,
 0x1.25ce26p+4, 0x1.2a9f2cp+4, 0x1.2f703p+4, 0x1.344136p+4, 0x1.39123ap+4,
 0x1.3de33ep+4, 0x1.42b444p+4, 0x1.478548p+4, 0x1.4c564ep+4, 0x1.512752p+4,
 0x1.55f856p+4, 0x1.5ac95cp+4, 0x1.5f9a6p+4, 0x1.646b66p+4, 0x1.693c6ap+4,
 0x1.6e0d6ep+4, 0x1.72de74p+4, 0x1.77af78p+4, 0x1.7c807ep+4, 0x1.815182p+4,
 0x1.862288p+4, 0x1.8af38cp+4, 0x1.8fc49p+4, 0x1.949596p+4, 0x1.99669ap+4,
 0x1.9e37ap+4, 0x1.a308a4p+4, 0x1.a7d9a8p+4, 0x1.acaaaep+4, 0x1.b17bb2p+4,
 0x1.b64cb8p+4, 0x1.bb1dbcp+4, 0x1.bfeec2p+4, 0x1.c4bfc6p+4, 0x1.c990cap+4,
 0x1.ce61dp+4, 0x1.d332d4p+4, 0x1.d803dap+4, 0x1.dcd4dep+4, 0x1.e1a5e2p+4,
 0x1.e676e8p+4, 0x1.eb47ecp+4, 0x1.f018f2p+4, 0x1.f4e9f6p+4, 0x1.f9bafcp+4,
 0x1.fe8cp+4, 0x1.01ae82p+5, 0x1.041704p+5, 0x1.067f88p+5, 0x1.08e80ap+5,
 0x1.0b508cp+5, 0x1.0db90ep+5, 0x1.10219p+5, 0x1.128a14p+5, 0x1.14f296p+5,
 0x1.175b18p+5, 0x1.19c39ap+5, 0x1.1c2c1cp+5, 0x1.1e94ap+5, 0x1.20fd22p+5,
 0x1.2365a4p+5, 0x1.25ce26p+5, 0x1.2836a8p+5, 0x1.2a9f2cp+5, 0x1.2d07aep+5,
 0x1.2f703p+5, 0x1.31d8b2p+5, 0,
};

/* For 0 <= i2 < 2^7, T2[i2] approximates log10(x2), where 1 <= x2 < 2
   and i2 matches the 7 lower bits of the 16-bit encoding of x2.
   Table generated by table2() in log.sage, with some entries manually
   edited to avoid exceptional cases (for x=10, 100, 1000). */
static const float T2[] = {
 0x0p+0, 0x1.bafd48p-9, 0x1.b9476ap-8, 0x1.49b086p-7, 0x1.b5e908p-7,
 0x1.10a83ap-6, 0x1.45f4f6p-6, 0x1.7adc3ep-6, 0x1.af5f92p-6, 0x1.e3806ap-6,
 0x1.0ba01ap-5, 0x1.25502cp-5, 0x1.3ed11ap-5, 0x1.58238ep-5, 0x1.714834p-5,
 0x1.8a3faep-5, 0x1.a30a9ep-5, 0x1.bba9ap-5, 0x1.d41d52p-5, 0x1.ec6648p-5,
 0x1.02428cp-4, 0x1.0e3d2ap-4, 0x1.1a2344p-4, 0x1.25f522p-4, 0x1.31b306p-4,
 0x1.3d5d34p-4, 0x1.48f3eep-4, 0x1.547774p-4, 0x1.5fe804p-4, 0x1.6b45ep-4,
 0x1.76914p-4, 0x1.81ca64p-4, 0x1.8cf18p-4, 0x1.9806dap-4, 0x1.a30a9ep-4,
 0x1.adfd08p-4, 0x1.b8de4ep-4, 0x1.c3aea4p-4, 0x1.ce6e42p-4, 0x1.d91d58p-4,
 0x1.e3bc1ap-4, 0x1.ee4abap-4, 0x1.f8c968p-4, 0x1.019c2ap-3, 0x1.06cbd6p-3,
 0x1.0bf3dp-3, 0x1.11143p-3, 0x1.162d08p-3, 0x1.1b3e72p-3, 0x1.204882p-3,
 0x1.254b4ep-3, 0x1.2a46e8p-3, 0x1.2f3b6ap-3, 0x1.3428e2p-3, 0x1.390f68p-3,
 0x1.3def0ep-3, 0x1.42c7e8p-3, 0x1.479a08p-3, 0x1.4c658p-3, 0x1.512a64p-3,
 0x1.55e8c6p-3, 0x1.5aa0b4p-3, 0x1.5f5244p-3, 0x1.63fd86p-3, 0x1.68a288p-3,
 0x1.6d415ep-3, 0x1.71da18p-3, 0x1.766cc4p-3, 0x1.7af974p-3, 0x1.7f8036p-3,
 0x1.84011ap-3, 0x1.887c2ep-3, 0x1.8cf18p-3, 0x1.916128p-3, 0x1.95cb28p-3,
 0x1.9a2f96p-3, 0x1.9e8e7cp-3, 0x1.a2e7e8p-3, 0x1.a73beap-3, 0x1.ab8a9p-3,
 0x1.afd3e4p-3, 0x1.b417f4p-3, 0x1.b856dp-3, 0x1.bc908p-3, 0x1.c0c514p-3,
 0x1.c4f496p-3, 0x1.c91f14p-3, 0x1.cd4498p-3, 0x1.d1653p-3, 0x1.d580e6p-3,
 0x1.d997c8p-3, 0x1.dda9dep-3, 0x1.e1b734p-3, 0x1.e5bfd6p-3, 0x1.e9c3cep-3,
 0x1.edc328p-3, 0x1.f1bdeep-3, 0x1.f5b42ap-3, 0x1.f9a5e8p-3, 0x1.fd933p-3,
 0x1.00be06p-2, 0x1.02b044p-2, 0x1.04a054p-2, 0x1.068e4p-2, 0x1.087a08p-2,
 0x1.0a63b4p-2, 0x1.0c4b46p-2, 0x1.0e30c4p-2, 0x1.101432p-2, 0x1.11f594p-2,
 0x1.13d4fp-2, 0x1.15b24ap-2, 0x1.178da6p-2, 0x1.196706p-2, 0x1.1b3e72p-2,
 0x1.1d13ecp-2, 0x1.1ee778p-2, 0x1.20b91ap-2, 0x1.2288d8p-2, 0x1.2456b4p-2,
 0x1.2622bp-2, 0x1.27ecd4p-2, 0x1.29b52p-2, 0x1.2b7b9ep-2, 0x1.2d404cp-2,
 0x1.2f032cp-2, 0x1.30c448p-2, 0x1.32839ep-2,
};

/* For 0 <= i2 < 2^7, T3[i2] approximates log10(x2), where x2 is
   subnormal, and i2 equals the 16-bit encoding of x2.
   Table generated by table3() in log.sage. */
static const b32u32_u T3[] = {
 {.u = 0xff800000}, {-0x1.404bc2p+5}, {-0x1.3de33ep+5}, {-0x1.3c7a9cp+5},
 {-0x1.3b7abcp+5}, {-0x1.3ab444p+5}, {-0x1.3a121ap+5}, {-0x1.3988fep+5},
 {-0x1.39123ap+5}, {-0x1.38a978p+5}, {-0x1.384bc2p+5}, {-0x1.37f6fcp+5},
 {-0x1.37a998p+5}, {-0x1.376266p+5}, {-0x1.37207cp+5}, {-0x1.36e31ep+5},
 {-0x1.36a9b8p+5}, {-0x1.3673ccp+5}, {-0x1.3640f4p+5}, {-0x1.3610dep+5},
 {-0x1.35e33ep+5}, {-0x1.35b7dap+5}, {-0x1.358e7ap+5}, {-0x1.3566fp+5},
 {-0x1.354114p+5}, {-0x1.351cc6p+5}, {-0x1.34f9e4p+5}, {-0x1.34d852p+5},
 {-0x1.34b7fap+5}, {-0x1.3498c4p+5}, {-0x1.347a9cp+5}, {-0x1.345d72p+5},
 {-0x1.344136p+5}, {-0x1.3425d6p+5}, {-0x1.340b4ap+5}, {-0x1.33f18p+5},
 {-0x1.33d872p+5}, {-0x1.33c014p+5}, {-0x1.33a85cp+5}, {-0x1.339142p+5},
 {-0x1.337abcp+5}, {-0x1.3364c6p+5}, {-0x1.334f56p+5}, {-0x1.333a6ap+5},
 {-0x1.3325f6p+5}, {-0x1.3311fap+5}, {-0x1.32fe6ep+5}, {-0x1.32eb4cp+5},
 {-0x1.32d892p+5}, {-0x1.32c63cp+5}, {-0x1.32b444p+5}, {-0x1.32a2a6p+5},
 {-0x1.329162p+5}, {-0x1.32807p+5}, {-0x1.326fdp+5}, {-0x1.325f7ep+5},
 {-0x1.324f78p+5}, {-0x1.323fb8p+5}, {-0x1.32304p+5}, {-0x1.32210cp+5},
 {-0x1.32121ap+5}, {-0x1.320366p+5}, {-0x1.31f4fp+5}, {-0x1.31e6b4p+5},
 {-0x1.31d8b2p+5}, {-0x1.31cae8p+5}, {-0x1.31bd54p+5}, {-0x1.31aff4p+5},
 {-0x1.31a2c6p+5}, {-0x1.3195cap+5}, {-0x1.3188fep+5}, {-0x1.317c6p+5},
 {-0x1.316ffp+5}, {-0x1.3163acp+5}, {-0x1.315792p+5}, {-0x1.314bap+5},
 {-0x1.313fdap+5}, {-0x1.313438p+5}, {-0x1.3128bep+5}, {-0x1.311d6ap+5},
 {-0x1.31123ap+5}, {-0x1.31072ep+5}, {-0x1.30fc44p+5}, {-0x1.30f17cp+5},
 {-0x1.30e6d4p+5}, {-0x1.30dc4ep+5}, {-0x1.30d1e6p+5}, {-0x1.30c79ep+5},
 {-0x1.30bd74p+5}, {-0x1.30b368p+5}, {-0x1.30a978p+5}, {-0x1.309fa4p+5},
 {-0x1.3095eap+5}, {-0x1.308c4ep+5}, {-0x1.3082cap+5}, {-0x1.30796p+5},
 {-0x1.30701p+5}, {-0x1.3066d8p+5}, {-0x1.305dbap+5}, {-0x1.3054b2p+5},
 {-0x1.304bc2p+5}, {-0x1.3042e8p+5}, {-0x1.303a24p+5}, {-0x1.303176p+5},
 {-0x1.3028dep+5}, {-0x1.30205cp+5}, {-0x1.3017eep+5}, {-0x1.300f94p+5},
 {-0x1.30074ep+5}, {-0x1.2fff1ap+5}, {-0x1.2ff6fcp+5}, {-0x1.2feeeep+5},
 {-0x1.2fe6f4p+5}, {-0x1.2fdf0cp+5}, {-0x1.2fd736p+5}, {-0x1.2fcf72p+5},
 {-0x1.2fc7bep+5}, {-0x1.2fc01cp+5}, {-0x1.2fb88ap+5}, {-0x1.2fb108p+5},
 {-0x1.2fa998p+5}, {-0x1.2fa236p+5}, {-0x1.2f9ae4p+5}, {-0x1.2f93ap+5},
 {-0x1.2f8c6ep+5}, {-0x1.2f8548p+5}, {-0x1.2f7e32p+5}, {-0x1.2f772ap+5},
};

__bf16 cr_log10_bf16 (__bf16 x){
  b16u16_u v = {.f = x};
  uint16_t u = v.u;
  uint16_t i1 = u >> 7;
  uint16_t i2 = u & 0x7f;
  static const b16u16_u nan = {.u = 0x7fc0}; // qNaN
  static const b16u16_u inf = {.u = 0x7f80}; // +Inf
  static const b16u16_u minus_inf = {.u = 0xff80}; // -Inf
  if (u >> 15) { // case -0 or x < 0
#ifdef CORE_MATH_SUPPORT_ERRNO
    errno = (x != 0) ? EDOM : ERANGE;
#endif
    // x + nan.f raises invalid if x = -sNaN
    return (u == 0x8000) ? minus_inf.f : x + nan.f;
  }
  if ((u >> 7) == 0xff) return inf.f + x; // NaN or Inf
  if (i1 == 0) { // subnormal case
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (i2 == 0)
      errno = ERANGE; // case x = +0
#endif
    return T3[i2].f;
  }
  return T1[i1] + T2[i2];
}

// dummy function since GNU libc does not provide it
__bf16 log10_bf16 (__bf16 x) {
  return (__bf16) log10f ((float) x);
}
