# Makefile for this SIMPLE setup for Reduce building

CC=gcc
CFLAGS=-m32 -O2 -DHAVE_CONFIG_H=1 -DEMBEDDED=1

all:	reduce

reduce:		arith01.o arith02.o arith03.o arith04.o arith05.o \
		arith06.o arith07.o arith08.o arith09.o arith10.o \
		arith11.o arith12.o bytes.o char.o \
		csl.o cslmpi.o cslread.o eval1.o eval2.o eval3.o \
		eval4.o fasl.o fns1.o fns2.o fns3.o fwin.o gc.o \
		preserve.o print.o restart.o sysfwin.o termed.o \
		u01.o u02.o u03.o u04.o u05.o u06.o u07.o u08.o u09.o u10.o \
		u11.o u12.o u13.o u14.o u15.o u16.o u17.o u18.o u19.o u20.o \
		u21.o u22.o u23.o u24.o u25.o u26.o u27.o u28.o u29.o u30.o \
		u31.o u32.o u33.o u34.o u35.o u36.o u37.o u38.o u39.o u40.o \
		u41.o u42.o u43.o u44.o u45.o u46.o u47.o u48.o u49.o u50.o \
		u51.o u52.o u53.o u54.o u55.o u56.o u57.o u58.o u59.o u60.o
	$(CC) $(CFLAGS) arith01.o arith02.o arith03.o arith04.o arith05.o \
	arith06.o arith07.o arith08.o arith09.o arith10.o \
	arith11.o arith12.o bytes.o char.o \
	csl.o cslmpi.o cslread.o eval1.o eval2.o eval3.o \
	eval4.o fasl.o fns1.o fns2.o fns3.o fwin.o gc.o \
	preserve.o print.o restart.o sysfwin.o termed.o \
	u01.o u02.o u03.o u04.o u05.o u06.o u07.o u08.o u09.o u10.o \
	u11.o u12.o u13.o u14.o u15.o u16.o u17.o u18.o u19.o u20.o \
	u21.o u22.o u23.o u24.o u25.o u26.o u27.o u28.o u29.o u30.o \
	u31.o u32.o u33.o u34.o u35.o u36.o u37.o u38.o u39.o u40.o \
	u41.o u42.o u43.o u44.o u45.o u46.o u47.o u48.o u49.o u50.o \
	u51.o u52.o u53.o u54.o u55.o u56.o u57.o u58.o u59.o u60.o \
	-lm -o reduce

clean:
	rm -f arith01.o arith02.o arith03.o arith04.o arith05.o \
		arith06.o arith07.o arith08.o arith09.o arith10.o \
		arith11.o arith12.o bytes.o char.o \
		csl.o cslmpi.o cslread.o eval1.o eval2.o eval3.o \
		eval4.o fasl.o fns1.o fns2.o fns3.o fwin.o gc.o \
		preserve.o print.o restart.o sysfwin.o termed.o \
		u01.o u02.o u03.o u04.o u05.o u06.o u07.o u08.o u09.o u10.o \
		u11.o u12.o u13.o u14.o u15.o u16.o u17.o u18.o u19.o u20.o \
		u21.o u22.o u23.o u24.o u25.o u26.o u27.o u28.o u29.o u30.o \
		u31.o u32.o u33.o u34.o u35.o u36.o u37.o u38.o u39.o u40.o \
		u41.o u42.o u43.o u44.o u45.o u46.o u47.o u48.o u49.o u50.o \		u51.o u52.o u53.o u54.o u55.o u56.o u57.o u58.o u59.o u60.o \
		u51.o u52.o u53.o u54.o u55.o u56.o u57.o u58.o u59.o u60.o

# end of Makefile
