/* Correctly-rounded hyperbolic tangent function for bfloat16 value.

Copyright (c) 2025 Paul Zimmermann

This file is part of the CORE-MATH project
(https://core-math.gitlabpages.inria.fr/).

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <stdint.h>
#include <errno.h>
#include <math.h> // only used during performance tests

// Warning: clang also defines __GNUC__
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#endif

#pragma STDC FENV_ACCESS ON

typedef union {__bf16 f; uint16_t u;} b16u16_u;

/* For 0 <= i1 <= 91, S1[i1] stores the binary32 approximation of sinh(x1)
   to nearest, where the bfloat16 encoding of x1 is 123*2^7+i1*2^3,
   Table generated by tableS1() from tanh.sage. */
static const float S1[] = {
 0x1.002aacp-4, 0x1.10333p-4, 0x1.203cc4p-4, 0x1.304778p-4, 0x1.40535cp-4,
 0x1.50608p-4, 0x1.606ef6p-4, 0x1.707ecap-4, 0x1.80901p-4, 0x1.90a2d6p-4,
 0x1.a0b72ep-4, 0x1.b0cd26p-4, 0x1.c0e4cep-4, 0x1.d0fe38p-4, 0x1.e11972p-4,
 0x1.f1368cp-4, 0x1.00aaccp-3, 0x1.10cce4p-3, 0x1.20f33ep-3, 0x1.311e1cp-3,
 0x1.414dbep-3, 0x1.518266p-3, 0x1.61bc52p-3, 0x1.71fbc8p-3, 0x1.824104p-3,
 0x1.928c48p-3, 0x1.a2ddd8p-3, 0x1.b335f4p-3, 0x1.c394dcp-3, 0x1.d3fad2p-3,
 0x1.e46818p-3, 0x1.f4dcfp-3, 0x1.02accep-2, 0x1.1335bap-2, 0x1.23cfdap-2,
 0x1.347c38p-2, 0x1.453bdcp-2, 0x1.560fd4p-2, 0x1.66f92ep-2, 0x1.77f8f8p-2,
 0x1.891042p-2, 0x1.9a401cp-2, 0x1.ab899ap-2, 0x1.bcedd2p-2, 0x1.ce6dd8p-2,
 0x1.e00ac4p-2, 0x1.f1c5b2p-2, 0x1.01cfdep-1, 0x1.0acdp-1, 0x1.1cf9dep-1,
 0x1.2f6dfap-1, 0x1.422df2p-1, 0x1.553e7ap-1, 0x1.68a452p-1, 0x1.7c6454p-1,
 0x1.908372p-1, 0x1.a506b2p-1, 0x1.b9f338p-1, 0x1.cf4e3cp-1, 0x1.e51d16p-1,
 0x1.fb6538p-1, 0x1.09161cp+0, 0x1.14bbe2p+0, 0x1.20a6dap+0, 0x1.2cd9fcp+0,
 0x1.462508p+0, 0x1.60b656p+0, 0x1.7ca876p+0, 0x1.9a175ep+0, 0x1.b9208p+0,
 0x1.d9e2e8p+0, 0x1.fc7f5ap+0, 0x1.108c3ap+1, 0x1.23e96cp+1, 0x1.386a9ep+1,
 0x1.4e2454p+1, 0x1.652c4cp+1, 0x1.7d998ep+1, 0x1.978488p+1, 0x1.b3072ap+1,
 0x1.d03cf6p+1, 0x1.081c62p+2, 0x1.2c3c1ap+2, 0x1.550e54p+2, 0x1.83368cp+2,
 0x1.b76da6p+2, 0x1.f284bep+2, 0x1.1ab442p+3, 0x1.40926ep+3, 0x1.6b749p+3,
 0x1.9c066ap+3, 0x1.d30a82p+3,
};

/* For 0 <= i1 <= 91, C1[i1] stores the binary32 approximation of cosh(x1)
   to nearest, where the bfloat16 encoding of x1 is 123*2^7+i1*2^3,
   Table generated by tableC1() from tanh.sage. */
static const float C1[] = {
 0x1.00800ap+0, 0x1.00908ep+0, 0x1.00a212p+0, 0x1.00b496p+0, 0x1.00c81ap+0,
 0x1.00dcap+0, 0x1.00f226p+0, 0x1.0108aep+0, 0x1.012036p+0, 0x1.0138cp+0,
 0x1.01524ap+0, 0x1.016cd6p+0, 0x1.018864p+0, 0x1.01a4f4p+0, 0x1.01c284p+0,
 0x1.01e116p+0, 0x1.0200aap+0, 0x1.0242dap+0, 0x1.028912p+0, 0x1.02d354p+0,
 0x1.0321a2p+0, 0x1.0373fap+0, 0x1.03ca62p+0, 0x1.0424dap+0, 0x1.048362p+0,
 0x1.04e5fap+0, 0x1.054ca8p+0, 0x1.05b76ap+0, 0x1.062644p+0, 0x1.069936p+0,
 0x1.071042p+0, 0x1.078b6ap+0, 0x1.080abp+0, 0x1.0915ap+0, 0x1.0a3122p+0,
 0x1.0b5d46p+0, 0x1.0c9a2p+0, 0x1.0de7c4p+0, 0x1.0f4648p+0, 0x1.10b5bep+0,
 0x1.12364p+0, 0x1.13c7e8p+0, 0x1.156acap+0, 0x1.171f04p+0, 0x1.18e4aep+0,
 0x1.1abbe8p+0, 0x1.1ca4cep+0, 0x1.1e9f7ep+0, 0x1.20ac18p+0, 0x1.24fb9p+0,
 0x1.299446p+0, 0x1.2e7764p+0, 0x1.33a622p+0, 0x1.3921cap+0, 0x1.3eebbcp+0,
 0x1.45056cp+0, 0x1.4b705ep+0, 0x1.522e2cp+0, 0x1.59408ap+0, 0x1.60a93ap+0,
 0x1.686a14p+0, 0x1.70850cp+0, 0x1.78fc28p+0, 0x1.81d182p+0, 0x1.8b0756p+0,
 0x1.9e9dacp+0, 0x1.b3d2c2p+0, 0x1.cabbdp+0, 0x1.e36fcp+0, 0x1.fe0746p+0,
 0x1.0d4e8p+1, 0x1.1ca6c2p+1, 0x1.2d1bc2p+1, 0x1.3ebdf8p+1, 0x1.519f04p+1,
 0x1.65d1cep+1, 0x1.7b6a86p+1, 0x1.927ec8p+1, 0x1.ab25acp+1, 0x1.c577d8p+1,
 0x1.e18fap+1, 0x1.0fc12cp+2, 0x1.32faf6p+2, 0x1.5b0246p+2, 0x1.88776ep+2,
 0x1.bc108p+2, 0x1.f69c24p+2, 0x1.1c826ap+3, 0x1.422a4ap+3, 0x1.6cdc7ep+3,
 0x1.9d440ep+3, 0x1.d422d2p+3,
};

/* For 0 <= i2 <= 47, S2[i2] stores the binary32 approximation of sinh(x2)
   to nearest, where x2 = 2^(h-11)*l, i2 decomposes into 2^3*h+l,
   0 <= h < 2^4, 0 <= l < 2^3.
   Table generated by tableS2() from tanh.sage. */
static const float S2[] = {
 0x0p+0, 0x1p-11, 0x1.000002p-10, 0x1.80000ap-10, 0x1.00000ap-9,
 0x1.400014p-9, 0x1.800024p-9, 0x1.c0003ap-9, 0x0p+0, 0x1.000002p-10,
 0x1.00000ap-9, 0x1.800024p-9, 0x1.00002ap-8, 0x1.400054p-8, 0x1.80009p-8,
 0x1.c000e4p-8, 0x0p+0, 0x1.00000ap-9, 0x1.00002ap-8, 0x1.80009p-8,
 0x1.0000aap-7, 0x1.40014ep-7, 0x1.80024p-7, 0x1.c00392p-7, 0x0p+0,
 0x1.00002ap-8, 0x1.0000aap-7, 0x1.80024p-7, 0x1.0002aap-6, 0x1.400536p-6,
 0x1.8009p-6, 0x1.c00e4ap-6, 0x0p+0, 0x1.0000aap-7, 0x1.0002aap-6,
 0x1.8009p-6, 0x1.000aaap-5, 0x1.4014d6p-5, 0x1.802402p-5, 0x1.c0392cp-5,
 0x0p+0, 0x1.0002aap-6, 0x1.000aaap-5, 0x1.802402p-5, 0x1.002aacp-4,
 0x1.40535cp-4, 0x1.80901p-4, 0x1.c0e4cep-4,
};

/* For 0 <= i2 <= 47, C2[i2] stores the binary32 approximation of cosh(x2)
   to nearest, where x2 = 2^(h-11)*l, i2 decomposes into 2^3*h+l,
   0 <= h < 2^4, 0 <= l < 2^3.
   Table generated by tableC2() from tanh.sage. */
static const float C2[] = {
 0x1p+0, 0x1.000002p+0, 0x1.000008p+0, 0x1.000012p+0, 0x1.00002p+0,
 0x1.000032p+0, 0x1.000048p+0, 0x1.000062p+0, 0x1p+0, 0x1.000008p+0,
 0x1.00002p+0, 0x1.000048p+0, 0x1.00008p+0, 0x1.0000c8p+0, 0x1.00012p+0,
 0x1.000188p+0, 0x1p+0, 0x1.00002p+0, 0x1.00008p+0, 0x1.00012p+0, 0x1.0002p+0,
 0x1.00032p+0, 0x1.00048p+0, 0x1.00062p+0, 0x1p+0, 0x1.00008p+0, 0x1.0002p+0,
 0x1.00048p+0, 0x1.0008p+0, 0x1.000c8p+0, 0x1.0012p+0, 0x1.00188p+0, 0x1p+0,
 0x1.0002p+0, 0x1.0008p+0, 0x1.0012p+0, 0x1.002p+0, 0x1.003202p+0,
 0x1.004804p+0, 0x1.006206p+0, 0x1p+0, 0x1.0008p+0, 0x1.002p+0, 0x1.004804p+0,
 0x1.00800ap+0, 0x1.00c81ap+0, 0x1.012036p+0, 0x1.018864p+0,
};

__bf16 cr_tanh_bf16 (__bf16 x){
  b16u16_u v = {.f = x};
  uint16_t u = v.u, au = u & 0x7fff;

  static const float sgn[] = {1.0, -1.0};

  // for |x| <= 0x1.7p-4, tanh(x) rounds to x to nearest
  if (au <= 0x3db8) { // |x| <= 0x1.7p-4
    if (au == 0) return x; // x = +0 or -0
    float res;
    // avoid spurious underflow for |x|=0x1p-126
    res = (au == 0x80) ? sgn[u>>15] * 0x1.fffffcp-127f
      : x * 0x1.fffffep-1f; // tanh(x) = x - x^3/6 + o(x^3)
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (__builtin_fabsf (res) < 0x1p-126)
      errno = ERANGE; // underflow
#endif
    return res;
  }

  // now 0x3db8 < au, |x| > 0x1.7p-4

  // for |x| >= 0x1.bcp+1, tanh(x) rounds to +/-1 to nearest
  if (au >= 0x405e) {
    if (0x7f80 <= au) { // Inf or NaN
      if (au == 0x7f80) return (au == u) ? 1.0f : -1.0f; // Inf
      return x + x; // NaN
    }
    return (au == u) ? 0x1.fffffep-1f : -0x1.fffffep-1f;
  }

  // now 0x3de8 < au < 0x405e
  // the exponent part lies in [123,128]
  uint16_t i1 = (au - 0x3d80) >> 3; // 0x3d80 is 123<<7, i1 <= 91
  uint16_t i2 = (((au - 0x3d80) >> 7) << 3) | (au & 0x7); // i2 <= 47
  // we use a FMA to fix the evaluation order
  float s = __builtin_fmaf (S1[i1], C2[i2], C1[i1] * S2[i2]);
  float c = __builtin_fmaf (C1[i1], C2[i2], S1[i1] * S2[i2]);
  return sgn[u>>15] * (s/c);
}

// dummy function since GNU libc does not provide it
__bf16 tanh_bf16 (__bf16 x) {
  return (__bf16) sinhf ((float) x);
}
