.\" --------------------------------------------------------------------
.\" $Id$
.\" --------------------------------------------------------------------
.\" Copyright (c) 2006-2009 Thomas Sturm
.\" --------------------------------------------------------------------
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\"    * Redistributions of source code must retain the relevant
.\"      copyright notice, this list of conditions and the following
.\"      disclaimer.
.\"    * Redistributions in binary form must reproduce the above
.\"      copyright notice, this list of conditions and the following
.\"      disclaimer in the documentation and/or other materials provided
.\"      with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"

.TH "REDFRONT" "1" "21 Oct 2006" "REDFRONT 2.1"
.SH NAME
\fBredfront\fR \- REDUCE frontend
.SH SYNOPSIS
\fBredfront\fR [-bh] [[\-m] \fInumber\fP[kKmM]]
.SH DESCRIPTION
\fBredfront\fR is a terminal-based interactive frontend for the REDUCE
computer algebra system. It uses the GNU readline(3) to provide
editing facilities.
.PP
This man page only covers \fBredfront\fR. For information on REDUCE
find its documentation at http://www.reduce-algebra.com/ .
.SH "COMMANDS"
.IP \fInumber\fP[kKmM] 14
For a a PSL-based REDUCE, specify the number of bytes used for the
Lisp heap. Case insensitive k ("kilo") is expanded to 000, and m
("mega") is expanded to 000000.

On PSL based 64 bit systems, heap sizes less than one million are
multiplied on the REDUCE side by one million. This happens after the
expansion of k and m. For instance, 1 = 1m yields 1 MB, and 1k yields
1000 MB. Consequently, k denotes GB until 1000k, which is again 1 MB.
At present, this mechanism should be used in order to avoid a possible
integer overflow in the heap size argument to the underlying binary
PSL.
.SH "OPTIONS"
.IP \-b 5
Black-and-white mode. That is, do not adjust any terminal colors.
.IP \-h 5
Print a short help message
.IP \-m NUMBER[kKmM] 5
Pass the heap size as an option instead of as a command.
.SH "SEE ALSO"
readline(3).
.SH "FILES"
~/.reduce_history stores command history between sessions.
.SH "AUTHORS"
Andreas Dolzmann and Thomas Sturm, University of Passau, Germany.
The project has been derived from an earlier version by Winfried Neun,
Konrad-Zuse-Zentrum fuer Informationstechnik, Berlin, Germany.
.SH "BUG REPORTS"
Please send bug reports and comments to \fIredlog@fmi.uni-passau.de\fP.
.SH "BUGS"
For redfront 1 KB is 1000 Bytes in contrast to 1024, 1 MB is 1000 KB,
and so on.

PSL based REDUCE on 32 bit systems generally do not admit more than
128m heap size. On some systems (e.g. Mac G4, Solaris) this even
reduces to 64m. On some architectures the command and the \-m option
are generally ignored on the REDUCE side. The heap is then set to the
maximum possible size.

The special treatment of heap size arguments by 64 bit PSL based
REDUCE should be revised.
