#!/bin/sh

# check the log files for all modules

# main log files go in ../../../log/*.rlg,
# reference ones are in ../../../packages/XXX/XXX.rlg

./r37 -Dno_init_file ../util/checkall.red -Dwhich_module=$1 -- log/checkall.log


