#!/bin/sh

# profile all modules

# results go to "profile.dat"

# Note: on a 400 MHz Pentium II this uses around 1 hour of CPU time.

./slowr37 -v -i slowr37.img -Dno_init_file ../util/profile.red -- log/profile.log


