#!/bin/sh

# test all modules but using the bootstrap (slow) version of REDUCE

# main log files go in ../../../log/*.rlg

./slowr37 -v ../util/testall.red -Dno_init_file -Dwhich_module=$1 -- log/testslow.log


