#!/bin/csh -f

# dbuild --- Build a minimal REDUCE sufficient to build all fasl files.

# Author: Anthony C. Hearn.

rm -f $reduce/log/dbuild.log $reduce/reduce

date > $reduce/log/dbuild.log

pushd $reduce/psl

bpsl -td 5000000 -b 0.30 -h 0.70 >>& $reduce/log/dbuild.log << EOF

(setq symbolfilename* "\$reduce/psl/bpsl")

(setq loaddirectories!* '("" "\$reduce/psl/"))

(cd "$reduce/src")

(dskin "dbuild.sl")

(setq loaddirectories!* '("" "\$reduce/psl/" "\$reduce/fasl/"))

(savesystem "Base REDUCE 3.4" "$reduce/reduce" nil)

(bye)

EOF

popd

date >> $reduce/log/dbuild.log
