#!/bin/csh -f

# mkfasl --- Make a fasl file.

# Author: Anthony C. Hearn.

rm -f $reduce/log/mk$1.log

$reduce/reduce >& $reduce/log/mk$1.log << EOF

symbolic;

% Compiler loading and modifications.

dskin "$reduce/src/symget.dat";         % Fast symprp access
load compiler;
remprop('wplus2,'one);                  % For hilbertp.
remprop('log,'no!-side!-effects!?);     % So that math can be fasled.
remprop('atan,'no!-side!-effects!?);    % So that math can be fasled.
load fast!-vector;                      % To use IGETV, etc.

dskin "$reduce/src/compat.sl";          % Some improvements ?!

!*verboseload := t;   % To help debugging.
!*fastcar := t;       % Since we assume all car/cdr calls are correct.

for each x in '( $3 ) do eval list('load, x);  % $3 is normally null.

faslout "$reduce/fasl/$1";
in "$reduce/src/$1.red"\$
faslend;

showtime;

bye;

EOF
