<footer class="col-xl-3 order-last">
	<hr  class="d-display d-xl-none" />
	<p>Page last modified on <?= date('l jS F Y', filemtime($_SERVER['SCRIPT_FILENAME'])); ?>.</p>
	<p>All information available through this web site is Copyright &copy; Anthony C. Hearn and the <a href="https://sourceforge.net/p/reduce-algebra/_members/">REDUCE developers</a> 2009&ndash;2018. All Rights Reserved.</p>
	<p>Please report broken links (both in-coming and out-going), other errors or suggestions for improvement to the <a href="https://sourceforge.net/users/fjwright/">webmaster</a>.</p>
</footer>
