<footer>
	<p>Page last modified on <?= date('l jS F Y', filemtime($_SERVER['SCRIPT_FILENAME'])); ?></p>
	<p>All information available through this web site is Copyright &copy; Anthony C. Hearn 2009&ndash;2017, all Rights Reserved.</p>
	<p>Please report broken links (both in-coming and out-going), other errors or suggestions for improvement to <a href="https://sourceforge.net/users/fjwright/">webmaster</a>.</p>
</footer>
