#!/bin/csh -f

# build --- Build REDUCE.

# Author: Anthony C. Hearn.

# This script is designed to build a complete set of REDUCE fast loading
# modules from source alone.  It should be used when the existing set of
# fast loading files is so corrupted that files can not be recompiled
# from an existing LISP, or a new REDUCE implementation is needed.

# First make basic REDUCE image

$reduce/util/dbuild

# Now compile all fasl files

$reduce/util/xbuild
