#!/bin/csh -f

# mkreduce --- Make basic REDUCE executable file.

# Author: Anthony C. Hearn.

rm -f $reduce/reduce $reduce/log/mkreduce.log

pushd $reduce/psl

set command='./bpsl -td 8000000 -b 0.27 -h 0.73'

$command >>& $reduce/log/mkreduce.log << EOF

(setq symbolfilename* "$reduce/psl/bpsl")

(setq loaddirectories!* '("" "$reduce/fasl/" "$reduce/psl/"))

(dskin "$reduce/src/mkreduce.sl")

(savesystem "REDUCE 3.4" "$reduce/reduce" nil)

(bye)

EOF

popd
