#!/bin/csh -f

# test-all --- Run all REDUCE Test Files.

# Author: Anthony C. Hearn.

date

# Standard Tests

foreach x (reduce math rounded complex elem decompos factor gcd int matrix \
           solve limits roots sum)
   $reduce/util/test $x
end

# Tests of Contributed Packages

foreach x (algint arnum excalc gentran groebner scope taylor \
           spde tps compact orthovec avector)
   $reduce/util/test $x $x
end

date
