// All methose needed for an arithmetic operation that will return a
// boolean value. Copyright (C) Codemist 2026.

    static bool op(std::intptr_t a);
    static bool op(uint64_t *a);
    static bool op(Rat a);
    static bool op(Cpx a);
    static bool op(SFlt a);
    static bool op(Flt a);
    static bool op(double a);
    static bool op(FLOAT_128 a);
    static bool op(std::intptr_t a, std::intptr_t b);
    static bool op(uint64_t *a, std::intptr_t b);
    static bool op(Rat a, std::intptr_t b);
    static bool op(Cpx a, std::intptr_t b);
    static bool op(SFlt a, std::intptr_t b);
    static bool op(Flt a, std::intptr_t b);
    static bool op(double a, std::intptr_t b);
    static bool op(FLOAT_128 a, std::intptr_t b);
    static bool op(std::intptr_t a, uint64_t *b);
    static bool op(uint64_t *a, uint64_t *b);
    static bool op(Rat a, uint64_t *b);
    static bool op(Cpx a, uint64_t *b);
    static bool op(SFlt a, uint64_t *b);
    static bool op(Flt a, uint64_t *b);
    static bool op(double a, uint64_t *b);
    static bool op(FLOAT_128 a, uint64_t *b);
    static bool op(std::intptr_t a, Rat b);
    static bool op(uint64_t *a, Rat b);
    static bool op(Rat a, Rat b);
    static bool op(Cpx a, Rat b);
    static bool op(SFlt a, Rat b);
    static bool op(Flt a, Rat b);
    static bool op(double a, Rat b);
    static bool op(FLOAT_128 a, Rat b);
    static bool op(std::intptr_t a, Cpx b);
    static bool op(uint64_t *a, Cpx b);
    static bool op(Rat a, Cpx b);
    static bool op(Cpx a, Cpx b);
    static bool op(SFlt a, Cpx b);
    static bool op(Flt a, Cpx b);
    static bool op(double a, Cpx b);
    static bool op(FLOAT_128 a, Cpx b);
    static bool op(std::intptr_t a, SFlt b);
    static bool op(uint64_t *a, SFlt b);
    static bool op(Rat a, SFlt b);
    static bool op(Cpx a, SFlt b);
    static bool op(SFlt a, SFlt b);
    static bool op(Flt a, SFlt b);
    static bool op(double a, SFlt b);
    static bool op(FLOAT_128 a, SFlt b);
    static bool op(std::intptr_t a, Flt b);
    static bool op(uint64_t *a, Flt b);
    static bool op(Rat a, Flt b);
    static bool op(Cpx a, Flt b);
    static bool op(SFlt a, Flt b);
    static bool op(Flt a, Flt b);
    static bool op(double a, Flt b);
    static bool op(FLOAT_128 a, Flt b);
    static bool op(std::intptr_t a, double b);
    static bool op(uint64_t *a, double b);
    static bool op(Rat a, double b);
    static bool op(Cpx a, double b);
    static bool op(SFlt a, double b);
    static bool op(Flt a, double b);
    static bool op(double a, double b);
    static bool op(FLOAT_128 a, double b);
    static bool op(std::intptr_t a, FLOAT_128 b);
    static bool op(uint64_t *a, FLOAT_128 b);
    static bool op(Rat a, FLOAT_128 b);
    static bool op(Cpx a, FLOAT_128 b);
    static bool op(SFlt a, FLOAT_128 b);
    static bool op(Flt a, FLOAT_128 b);
    static bool op(double a, FLOAT_128 b);
    static bool op(FLOAT_128 a, FLOAT_128 b);
};
// end of boolean class
