#! /bin/sh
a=$0
c=unknown
case $a in
/* )
  c=$a  
  ;;
*/* )
  case $a in
  ./* )
    a=`echo $a | sed -e s+./++`
    ;;
  esac
  c=`pwd`/$a
  ;;
* ) 
  for d in $PATH
  do
    if test -x $d/$a
    then
      c=$d/$a
    fi
  done
  if test $c = "unknown" ;then
    echo "Unable to find full path for script. Please re-try"
    echo "launching it using a fully rooted path."
    exit 1
  fi
  ;;
esac
while test -h "$c"; do
  lt=`ls -l "$c" | sed 's/.*->[ ][ ]*//'`
  if echo "$lt" | grep -q '^/'; then
    c="$lt"
  else
    dir=`dirname "$c"`
    c="$dir/$lt"
  fi
done
here=`echo $c | sed -e 's+/[^/]*$++'`

if $here/not-under-cygwin.exe $*
then
  $here/bootstrapreduce.exe $*
else
  $here/cygwin64-isatty.exe $* 2>/dev/null
  case $? in
  1)
    $here/cygwin64-bootstrapreduce.exe $*
    ;;
  esac
  $here/cygwin-isatty.exe $*
  case $? in
  0)
    $here/bootstrapreduce.exe --gui $*
    ;;
  1)
    $here/cygwin-bootstrapreduce.exe $*
    ;;
  2)
    $here/bootstrapreduce.exe $*
    ;;
  esac
fi
