#! /bin/sh
a=$0
c=unknown
case $a in
/* )
  c=$a  
  ;;
*/* )
  case $a in
  ./* )
    a=`echo $a | sed -e s+./++`
    ;;
  esac
  c=`pwd`/$a
  ;;
* ) 
  for d in $PATH
  do
    if test -x $d/$a
    then
      c=$d/$a
    fi
  done
  if test $c = "unknown" ;then
    echo "Unable to find full path for script. Please re-try"
    echo "launching it using a fully rooted path."
    exit 1
  fi
  ;;
esac
while test -h "$c"; do
  lt=`ls -l "$c" | sed 's/.*->[ ][ ]*//'`
  if echo "$lt" | grep -q '^/'; then
    c="$lt"
  else
    dir=`dirname "$c"`
    c="$dir/$lt"
  fi
done
here=`echo $c | sed -e 's+/[^/]*$++'`

if $here/not-under-cygwin.exe $*
then
  $here/csl.com $*
else
  case `uname -m` in
  *x86_64*)
    $here/cygwin64-isatty.exe $*
    case $? in
    0)
      $here/csl.com --gui $*
      ;;
    1)
      $here/cygwin64-csl.exe $*
      ;;
    *)
      $here/csl.com $*
      ;;
    esac
    ;;
  *i686*)
    $here/cygwin-isatty.exe $*
    case $? in
    0)
      $here/csl.com --gui $*
      ;;
    1)
      $here/cygwin-csl.exe $*
      ;;
    *)
      $here/csl.com $*
      ;;
    esac
  esac
fi
