#! /bin/sh
here=`dirname "$0"`
here=`cd "$here" ; pwd`
case $* in
*--cygwin*)
  case `uname -m` in
  *x86_64*)
    $here/cygwin64-csl.exe $*
    ;;
  *)
    $here/cygwin32-csl.exe $*
    ;;
  esac
  ;;
*)
  if $here/not-under-cygwin.exe $*
  then
    $here/csl.com $*
  else
    case `uname -m` in
    *x86_64*)
      $here/cygwin64-isatty.exe $*
      case $? in
      0)
        $here/csl.com --gui $*
        ;;
      1)
        $here/cygwin64-csl.exe $*
        ;;
      *)
        $here/csl.com $*
        ;;
      esac
      ;;
    *i686*)
      $here/cygwin-isatty.exe $*
      case $? in
      0)
        $here/csl.com --gui $*
        ;;
      1)
        $here/cygwin-csl.exe $*
        ;;
      *)
        $here/csl.com $*
        ;;
      esac
    esac
  fi
esac
