// All the cases needed for an arithmetic operation.
// BSD license, Copyright (C) Codemist 2026

    static LispObject op(std::intptr_t a);
    static LispObject op(uint64_t *a);
    static LispObject op(Rat a);
    static LispObject op(Cpx a);
    static LispObject op(SFlt a);
    static LispObject op(Flt a);
    static LispObject op(double a);
    static LispObject op(FLOAT_128 a);
    static LispObject op(std::intptr_t a, std::intptr_t b);
    static LispObject op(uint64_t* a, std::intptr_t b);
    static LispObject op(Rat a, std::intptr_t b);
    static LispObject op(Cpx a, std::intptr_t b);
    static LispObject op(SFlt a, std::intptr_t b);
    static LispObject op(Flt a, std::intptr_t b);
    static LispObject op(double a, std::intptr_t b);
    static LispObject op(FLOAT_128 a, std::intptr_t b);
    static LispObject op(std::intptr_t a, uint64_t *b);
    static LispObject op(uint64_t *a, uint64_t *b);
    static LispObject op(Rat a, uint64_t *b);
    static LispObject op(Cpx a, uint64_t *b);
    static LispObject op(SFlt a, uint64_t *b);
    static LispObject op(Flt a, uint64_t *b);
    static LispObject op(double a, uint64_t *b);
    static LispObject op(FLOAT_128 a, uint64_t *b);
    static LispObject op(std::intptr_t a, Rat b);
    static LispObject op(uint64_t *a, Rat b);
    static LispObject op(Rat a, Rat b);
    static LispObject op(Cpx a, Rat b);
    static LispObject op(SFlt a, Rat b);
    static LispObject op(Flt a, Rat b);
    static LispObject op(double a, Rat b);
    static LispObject op(FLOAT_128 a, Rat b);
    static LispObject op(std::intptr_t a, Cpx b);
    static LispObject op(uint64_t *a, Cpx b);
    static LispObject op(Rat a, Cpx b);
    static LispObject op(Cpx a, Cpx b);
    static LispObject op(SFlt a, Cpx b);
    static LispObject op(Flt a, Cpx b);
    static LispObject op(double a, Cpx b);
    static LispObject op(FLOAT_128 a, Cpx b);
    static LispObject op(std::intptr_t a, SFlt b);
    static LispObject op(uint64_t *a, SFlt b);
    static LispObject op(Rat a, SFlt b);
    static LispObject op(Cpx a, SFlt b);
    static LispObject op(SFlt a, SFlt b);
    static LispObject op(Flt a, SFlt b);
    static LispObject op(double a, SFlt b);
    static LispObject op(FLOAT_128 a, SFlt b);
    static LispObject op(std::intptr_t a, Flt b);
    static LispObject op(uint64_t *a, Flt b);
    static LispObject op(Rat a, Flt b);
    static LispObject op(Cpx a, Flt b);
    static LispObject op(SFlt a, Flt b);
    static LispObject op(Flt a, Flt b);
    static LispObject op(double a, Flt b);
    static LispObject op(FLOAT_128 a, Flt b);
    static LispObject op(std::intptr_t a, double b);
    static LispObject op(uint64_t *a, double b);
    static LispObject op(Rat a, double b);
    static LispObject op(Cpx a, double b);
    static LispObject op(SFlt a, double b);
    static LispObject op(Flt a, double b);
    static LispObject op(double a, double b);
    static LispObject op(FLOAT_128 a, double b);
    static LispObject op(std::intptr_t a, FLOAT_128 b);
    static LispObject op(uint64_t *a, FLOAT_128 b);
    static LispObject op(Rat a, FLOAT_128 b);
    static LispObject op(Cpx a, FLOAT_128 b);
    static LispObject op(SFlt a, FLOAT_128 b);
    static LispObject op(Flt a, FLOAT_128 b);
    static LispObject op(double a, FLOAT_128 b);
    static LispObject op(FLOAT_128 a, FLOAT_128 b);
};
// end of this arithmetic operation.
