#!/bin/bash
ARCH="$($trunk/scripts/findhost.sh $($trunk/config.guess))"
RLSMT="$trunk/pslbuild/$ARCH/psl/bpsl -td 4000 -f $trunk/generic/rlsmt/rlsmt.img"
if [ "$1" != "" ]; then
    $RLSMT < $1
else
    $RLSMT
fi
