#! /bin/csh

#-------------------------------------------------------------
#
#  Compile REDUCE help info for GNU info format
#
#-------------------------------------------------------------

set package=redhelp
# if ("$1" != "") set package=$1

reduce <<EOF

ON ERRCONT;

symbolic;
on backtrace;
on comp;

in "comphelp.red"\$
in "helpunx.red"\$
in "minitex.red"\$
 
% TR minitex;
% package := "$1";

%if package="" then  << dir_src := "redref/"; package := "redref">>
%              else  dir_src := "packages/";

dir_src := "$reduce/doc/help/";
package := "redhelp";

job(bldmsg("%w.tex",package),"/dev/null");

<<
terpri();
prin2t "=================================================";
prin2t "  SECOND RUN ";
prin2t "=================================================";
>>;
job(bldmsg("%w.tex",package), bldmsg("%w.x",package));

in "sed.red"\$

bye;

EOF

rm redhelp.x
mv redhelp.y redhelp.x

# You now need:

# makeinfo  --no-split -o redhelp.info redhelp.x

# rm redhelp.x

# To use the resulting redhelp.info, you need the Gnu "info" program or Xr.
# Say "info -f redhelp.inf" in the former case.
