#!/bin/csh -f

# checkall --- Check all REDUCE Test Files against Exemplary logs.

# Author: Anthony C. Hearn.

rm -f $reduce/log/checkall.log

source $reduce/xpackage.bat

set xpackages=($xpackages $xpackages2 $xpackages3)

foreach x ($xpackages)
   perl $reduce/util/chckallp.pl $x
end
