#!/bin/csh -f

# Compile a single package.

# Author: Anthony C. Hearn.

rm -f $reduce/log/$1.blg

$reduce/reduce.$lisp >& $reduce/log/$1.blg << EOF

symbolic;

if getenv "lisp" = "csl"   % 'csl memq lispsystem!*
  then <<on backtrace;  % In case something goes wrong.
	 !*savedef := nil>>
 else <<load compiler;
	errorset('(load compat),nil,nil); % PSL compiler support.
        on verboseload;
	% Specific package loads to avoid BPS problems.
	if '$1 eq 'susy2 then flag('(susy2),'lap)
	 else if '$1 eq 'fps
	  then load_package limits,factor,specfn,sfgamma
	 else if '$1 eq 'mrvlimit then load_package taylor
	% Memory increases to avoid heap allocation problems.
	 else if getenv "MACHINE" neq "sunos" then nil
	 else if '$1 eq 'defint
	  then set_heap_size 1200000 % 1000000 too small.
	 else if '$1 memq '(specfn ztrans)
	  then set_heap_size 1000000  % 700000 is too small.
%        else if '$1 eq 'conlaw % Needs more ID space.
%         then <<load big!-faslend; initcodemax!* := 200>>
	>>;

load remake;

!*argnochk := t;

in "$reduce/package.red"\$

package!-remake '$1;

if !*faslp and flagp('$1,'core_package)
  then system "touch $reduce/lisp/$lisp/$MACHINE/mkreduce";

bye;
EOF
