Date: Fri, 5 Nov 93 16:15:43 +0100
From: melenk@sc.ZIB-Berlin.DE (Herbert Melenk)
Subject: help milestone

Finally I'm done with the help material. It took me much longer
as originally expected, but I think that the result justifies
the effort. Please pick up the following data sets:

408064:  /silo/herbert/redhelp/redref/helptar.Z  these are the .tex files

230217   /silo/herbert/redhelp/redref.hlp.Z      the windows binary help file

325179 /silo/herbert/redhelp/txt/txttar.Z        the bare ascii documents
                                                 thanks to Rainer.

If you want to have a look at the hypertext connections
as implemented in the windows help file:

- uncompress under unix
- move the .hlp file to a DOS-Windows (or NT) machine
- do one of
  (1) double click it with the windows file manager,
  (2) (NT only) enter the command line
       winhelp redref.hlp
  (3) install an icon with title
       REDUCE reference
     and command line
       winhelp <dir>\redref.hlp
     where <dir> is the path,
     and then double click the yellow question mark.

Mode (3) allows one to have the book as on line document available
independent of a reduce session. That is how Microsoft deliver deliver
their system documentation.

Please have also a look at the index which I have built
partially automatically, partially by inserting lots of
\index statements. E.g.
  push the Search button
   and then enter
      polynomial (or any other central item)
   as search item.

================================================================

When working on the material I first had started to keep track
of any modification, but I gave that up rather soon.

I have modified several formats - latex accepts the object still,
bit I didn't look at the dvi output. 330 is too much for printing
anyway.

General remarks regarding the information:

In some places I have modified the REDUCE kernel material substantially.
I am sure that you will find better words for these points - I am happy
with *any* improvement. I ran spell on the data sets, but that does not
find bad grammar or wrong words.

Substantial points are:

   SOLVE+its sub-operators and switches
       ARBINT ARBCOMPLEX ROOT_OF ONE_OF EXPAND_CASES
       FULLROOTS FULLPREC

   RULE (new type)

   LET, WHEN, WHERE

   EQUATION

   BLOCK

   TRUE

======================================================
some details:
---------------------------------------------------------

numeric.tex

I don't like the heading of this chapter, as most of the
operators described here are more general than just
numeric. How about "Arithmetic Operators?"

---------------------------------------------------------
REMAINDER:

remainder(sin(2*x),x*y);                                &         SIN(2*X)
\end{Examples}

\begin{Comments}
If the first argument to \name{remainder} is not a polynomial, an error
occurs.

> Here the example and the comment contradict each other
>    sin(2*x) is *not* a polynomial
>>>> not repaired (I have no idea what to write here)

--------------------------------------------------------

boolean.tex


I have introduced a node which explains the meaning
of "true". This also could be a member of a "glossary".

The description of NOT

\meta{logical expression} must evaluate to {\it true} or {\it nil}.

is too restrictive. I have deleted this line.

----------------------------------------------------------

command.tex

not very important, but is WS a command? I would prefer
an operator because its main purpose is to deliver a value.

----------------------------------------------------------

algebra.tex

RESULTANT: please have a look at the TEX-parts: I think that
the 2nd polynomial should have a different degree (namely m
as in the INFO parts).

SOLVE: You sell SOLVE below its facilities. According to the
original description the following examples  would fail:

8: solve({x+y=1,x+2y=2,2x+3y=3},{x,y});

{{x=0,y=1}}

9: solve({x+y+z=1,x-y-z=1},{x,y,z});

{{x=1,y= - arbcomplex(4),z=arbcomplex(4)}}

Fortunately they don't! I have commented these restrictions
in the description.

--------------------------------------------------------

switch.tex

RATIONAL:

The \nameref{factorize} command does not accept
polynomials with rational coefficients.

> this is not true! I have commented this lines.

SOLVESINGULAR:

This switch seems to have no effect at all. At least the
example doesn't work. Is that a bug in solve or should
we remove this switch??

=============================================================

matrix.tex

Cofactor had a completely different syntax style

=============================================================

library.tex : upgraded from the current manual

======== EOF ===============================================
