(* ::Package:: *)

(* ::Title:: *)
(*Integration problems of the form (a+b x^n)^m (c+d x^n)^p (e+f x^n)^q*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x^2)^m (c+d x^2)^p (e+f x^2)^q*)


(* ::Subsection:: *)
(*Integrands of the form (a+b x^2)^m (c+d x^2)^p (e+f x^2)^q*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2)^m (c+d x^2)^p (e+f x^2)^(q/2)*)


{(a + b*x^2)^3/((c + d*x^2)*Sqrt[e + f*x^2]), x, 10, -((b^2*(b*c - a*d)*x*Sqrt[e + f*x^2])/(2*d^2*f)) - (3*b^2*(b*e - 2*a*f)*x*Sqrt[e + f*x^2])/(8*d*f^2) + (b^2*x*(a + b*x^2)*Sqrt[e + f*x^2])/(4*d*f) - ((b*c - a*d)^3*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d^3*Sqrt[d*e - c*f]) + (b*(b*c - a*d)^2*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d^3*Sqrt[f]) + (b*(b*c - a*d)*(b*e - 2*a*f)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(2*d^2*f^(3/2)) + (b*(3*b^2*e^2 - 8*a*b*e*f + 8*a^2*f^2)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(8*d*f^(5/2))}
{(a + b*x^2)^2/((c + d*x^2)*Sqrt[e + f*x^2]), x, 6, (b^2*x*Sqrt[e + f*x^2])/(2*d*f) + ((b*c - a*d)^2*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d^2*Sqrt[d*e - c*f]) - (b*(b*c - a*d)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d^2*Sqrt[f]) - (b*(b*e - 2*a*f)*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(2*d*f^(3/2))}
{(a + b*x^2)^1/((c + d*x^2)*Sqrt[e + f*x^2]), x, 3, -(((b*c - a*d)*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*d*Sqrt[d*e - c*f])) + (b*ArcTanh[(Sqrt[f]*x)/Sqrt[e + f*x^2]])/(d*Sqrt[f])}
{(a + b*x^2)^0/((c + d*x^2)*Sqrt[e + f*x^2]), x, 1, ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])]/(Sqrt[c]*Sqrt[d*e - c*f])}
{1/((a + b*x^2)^1*(c + d*x^2)*Sqrt[e + f*x^2]), x, 3, (b*ArcTan[(Sqrt[b*e - a*f]*x)/(Sqrt[a]*Sqrt[e + f*x^2])])/(Sqrt[a]*(b*c - a*d)*Sqrt[b*e - a*f]) - (d*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*(b*c - a*d)*Sqrt[d*e - c*f])}
{1/((a + b*x^2)^2*(c + d*x^2)*Sqrt[e + f*x^2]), x, 6, (b^2*x*Sqrt[e + f*x^2])/(2*a*(b*c - a*d)*(b*e - a*f)*(a + b*x^2)) + (b*(b*e - 2*a*f)*ArcTan[(Sqrt[b*e - a*f]*x)/(Sqrt[a]*Sqrt[e + f*x^2])])/(2*a^(3/2)*(b*c - a*d)*(b*e - a*f)^(3/2)) - (b*d*ArcTan[(Sqrt[b*e - a*f]*x)/(Sqrt[a]*Sqrt[e + f*x^2])])/(Sqrt[a]*(b*c - a*d)^2*Sqrt[b*e - a*f]) + (d^2*ArcTan[(Sqrt[d*e - c*f]*x)/(Sqrt[c]*Sqrt[e + f*x^2])])/(Sqrt[c]*(b*c - a*d)^2*Sqrt[d*e - c*f])}


{(a + b*x^2)*Sqrt[c + d*x^2]/(e + f*x^2), x, 4, (b*x*Sqrt[c + d*x^2])/(2*f) - ((2*b*d*e - b*c*f - 2*a*d*f)*ArcTanh[(Sqrt[d]*x)/Sqrt[c + d*x^2]])/(2*Sqrt[d]*f^2) + ((b*e - a*f)*Sqrt[d*e - c*f]*ArcTanh[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])])/(Sqrt[e]*f^2)}


{(a + b*x^2)/(Sqrt[c + d*x^2]*(e + f*x^2)^2), x, 3, ((b*e - a*f)*x*Sqrt[c + d*x^2])/(2*e*(d*e - c*f)*(e + f*x^2)) - ((b*c*e - 2*a*d*e + a*c*f)*ArcTanh[(Sqrt[d*e - c*f]*x)/(Sqrt[e]*Sqrt[c + d*x^2])])/(2*e^(3/2)*(d*e - c*f)^(3/2))}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x^2) (c+d x^2)^(p/2) (e+f x^2)^(q/2)*)


{(a + b*x^2)*(e + f*x^2)^(3/2)*(c + d*x^2)^(3/2), x, 9, ((9*a*d*f*(d^2*e^2 + 9*c*d*e*f - 2*c^2*f^2) - b*(4*d^3*e^3 - 9*c*d^2*e^2*f + 21*c^2*d*e*f^2 - 8*c^3*f^3))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(315*d^2*f^2) + ((18*a*d*f*(4*d*e - c*f) + b*(3*d^2*e^2 - 17*c*d*e*f + 8*c^2*f^2))*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(315*d^2*f) + ((3*b*d*e - 4*b*c*f + 9*a*d*f)*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(63*d^2) + (b*x*(c + d*x^2)^(5/2)*(e + f*x^2)^(3/2))/(9*d) - (Sqrt[e]*(18*a*d*f*(d^3*e^3 - 5*c*d^2*e^2*f - 5*c^2*d*e*f^2 + c^3*f^3) - b*(8*d^4*e^4 - 25*c*d^3*e^3*f + 18*c^2*d^2*e^2*f^2 - 25*c^3*d*e*f^3 + 8*c^4*f^4))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(315*d^3*(-f)^(5/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*Sqrt[e]*(d*e - c*f)*(9*a*d*f*(d^2*e^2 + 9*c*d*e*f - 2*c^2*f^2) - b*(4*d^3*e^3 - 9*c*d^2*e^2*f + 21*c^2*d*e*f^2 - 8*c^3*f^3))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(315*d^3*(-f)^(5/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)*(c + d*x^2)^(1/2), x, 8, ((14*a*d*f*(3*d*e - c*f) + b*(3*d^2*e^2 - 15*c*d*e*f + 8*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*d^2*f) + ((3*b*d*e - 4*b*c*f + 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*d^2) + (b*x*(c + d*x^2)^(3/2)*(e + f*x^2)^(3/2))/(7*d) - (Sqrt[e]*(7*a*d*f*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2) - b*(6*d^3*e^3 - 9*c*d^2*e^2*f + 19*c^2*d*e*f^2 - 8*c^3*f^3))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d^3*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(d*e - c*f)*(14*a*d*f*(3*d*e - c*f) + b*(3*d^2*e^2 - 15*c*d*e*f + 8*c^2*f^2))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d^3*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(1/2), x, 7, ((3*b*d*e - 4*b*c*f + 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*d^2) + (b*x*Sqrt[c + d*x^2]*(e + f*x^2)^(3/2))/(5*d) + (Sqrt[e]*(10*a*d*f*(2*d*e - c*f) + b*(3*d^2*e^2 - 13*c*d*e*f + 8*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d^3*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*(d*e - c*f)*(b*c*(9*d*e - 8*c*f) - 5*a*d*(3*d*e - 2*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d^3*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(3/2), x, 7, ((4*b*c - 3*a*d)*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*c*d^2) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(c*d*Sqrt[c + d*x^2]) - (Sqrt[e]*Sqrt[-f]*(b*c*(7*d*e - 8*c*f) - 3*a*d*(d*e - 2*c*f))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*d^3*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(d*e - c*f)*(3*b*d*e - 8*b*c*f + 6*a*d*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*d^3*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(5/2), x, 7, ((b*c*(d*e - 4*c*f) + a*d*(2*d*e + c*f))*x*Sqrt[e + f*x^2])/(3*c^2*d^2*Sqrt[c + d*x^2]) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(3*c*d*(c + d*x^2)^(3/2)) + (Sqrt[e]*Sqrt[-f]*(b*c*(d*e - 8*c*f) + 2*a*d*(d*e + c*f))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*d^3*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[-f]*(b*c*(5*d*e - 8*c*f) + a*d*(d*e + 2*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*d^3*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(7/2), x, 8, ((d*(b*c + 4*a*d)*e - c*(4*b*c + a*d)*f)*x*Sqrt[e + f*x^2])/(15*c^2*d^2*(c + d*x^2)^(3/2)) + ((b*c*(2*d^2*e^2 + 3*c*d*e*f - 8*c^2*f^2) + a*d*(8*d^2*e^2 - 3*c*d*e*f - 2*c^2*f^2))*x*Sqrt[e + f*x^2])/(15*c^3*d^2*(d*e - c*f)*Sqrt[c + d*x^2]) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(5*c*d*(c + d*x^2)^(5/2)) + (Sqrt[e]*Sqrt[-f]*(b*c*(2*d^2*e^2 + 3*c*d*e*f - 8*c^2*f^2) + a*d*(8*d^2*e^2 - 3*c*d*e*f - 2*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^3*d^3*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[-f]*(2*a*d*(2*d*e + c*f) + b*c*(d*e + 8*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^2*d^3*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(3/2)/(c + d*x^2)^(9/2), x, 9, ((d*(b*c + 6*a*d)*e - c*(4*b*c + 3*a*d)*f)*x*Sqrt[e + f*x^2])/(35*c^2*d^2*(c + d*x^2)^(5/2)) + ((b*c*(4*d^2*e^2 + c*d*e*f - 8*c^2*f^2) + 3*a*d*(8*d^2*e^2 - 5*c*d*e*f - 2*c^2*f^2))*x*Sqrt[e + f*x^2])/(105*c^3*d^2*(d*e - c*f)*(c + d*x^2)^(3/2)) + ((6*a*d*(8*d^3*e^3 - 12*c*d^2*e^2*f + 2*c^2*d*e*f^2 + c^3*f^3) + b*c*(8*d^3*e^3 - 5*c*d^2*e^2*f - 5*c^2*d*e*f^2 + 8*c^3*f^3))*x*Sqrt[e + f*x^2])/(105*c^4*d^2*(d*e - c*f)^2*Sqrt[c + d*x^2]) - ((b*c - a*d)*x*(e + f*x^2)^(3/2))/(7*c*d*(c + d*x^2)^(7/2)) + (Sqrt[e]*Sqrt[-f]*(6*a*d*(8*d^3*e^3 - 12*c*d^2*e^2*f + 2*c^2*d*e*f^2 + c^3*f^3) + b*c*(8*d^3*e^3 - 5*c*d^2*e^2*f - 5*c^2*d*e*f^2 + 8*c^3*f^3))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*c^4*d^3*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[-f]*(b*c*(4*d^2*e^2 + c*d*e*f - 8*c^2*f^2) + 3*a*d*(8*d^2*e^2 - 5*c*d*e*f - 2*c^2*f^2))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*c^3*d^3*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{(a + b*x^2)*(e + f*x^2)^(1/2)*(c + d*x^2)^(3/2), x, 8, ((7*a*d*f*(d*e + 3*c*f) - b*(4*d^2*e^2 - 6*c*d*e*f + 6*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*d*f^2) + ((b*d*e - 2*b*c*f + 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*d*f) + (b*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*d) - (Sqrt[e]*(7*a*d*f*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) - b*(8*d^3*e^3 - 19*c*d^2*e^2*f + 9*c^2*d*e*f^2 - 6*c^3*f^3))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d^2*(-f)^(5/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*Sqrt[e]*(d*e - c*f)*(7*a*d*f*(d*e + 3*c*f) - b*(4*d^2*e^2 - 6*c*d*e*f + 6*c^2*f^2))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d^2*(-f)^(5/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)*(c + d*x^2)^(1/2), x, 7, ((b*d*e - 2*b*c*f + 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*d*f) + (b*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*d) - (Sqrt[e]*(5*a*d*f*(d*e + c*f) - 2*b*(d^2*e^2 - c*d*e*f + c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d^2*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(d*e - c*f)*(b*d*e - 2*b*c*f + 5*a*d*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d^2*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(1/2), x, 6, (b*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*d) + (Sqrt[e]*(b*d*e - 2*b*c*f + 3*a*d*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*d^2*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((2*b*c - 3*a*d)*Sqrt[e]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*d^2*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(3/2), x, 6, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(c*d*Sqrt[c + d*x^2])) - ((2*b*c - a*d)*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*d^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(b*d*e - 2*b*c*f + a*d*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(d^2*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(5/2), x, 7, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(3*c*d*(c + d*x^2)^(3/2))) + ((d*(b*c + 2*a*d)*e - c*(2*b*c + a*d)*f)*x*Sqrt[e + f*x^2])/(3*c^2*d*(d*e - c*f)*Sqrt[c + d*x^2]) + (Sqrt[e]*Sqrt[-f]*(d*(b*c + 2*a*d)*e - c*(2*b*c + a*d)*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*d^2*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((2*b*c + a*d)*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*d^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)*(e + f*x^2)^(1/2)/(c + d*x^2)^(7/2), x, 8, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(5*c*d*(c + d*x^2)^(5/2))) + ((a*d*(4*d*e - 3*c*f) + b*c*(d*e - 2*c*f))*x*Sqrt[e + f*x^2])/(15*c^2*d*(d*e - c*f)*(c + d*x^2)^(3/2)) + ((2*b*c*(d^2*e^2 - c*d*e*f + c^2*f^2) + a*d*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*x*Sqrt[e + f*x^2])/(15*c^3*d*(d*e - c*f)^2*Sqrt[c + d*x^2]) + (Sqrt[e]*Sqrt[-f]*(2*b*c*(d^2*e^2 - c*d*e*f + c^2*f^2) + a*d*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^3*d^2*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[-f]*(a*d*(4*d*e - 3*c*f) + b*c*(d*e - 2*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^2*d^2*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(5/2), x, 8, -(((28*a*d*f*(d*e - 2*c*f) - b*(24*d^2*e^2 - 43*c*d*e*f + 15*c^2*f^2))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(105*f^3)) - ((6*b*d*e - 5*b*c*f - 7*a*d*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*f^2) + (b*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*f) - (Sqrt[e]*(7*a*d*f*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2) - b*(48*d^3*e^3 - 128*c*d^2*e^2*f + 103*c^2*d*e*f^2 - 15*c^3*f^3))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d*(-f)^(7/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*Sqrt[e]*(d*e - c*f)*(28*a*d*f*(d*e - 2*c*f) - b*(24*d^2*e^2 - 43*c*d*e*f + 15*c^2*f^2))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(105*d*(-f)^(7/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(3/2), x, 7, -(((4*b*d*e - 3*b*c*f - 5*a*d*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*f^2)) + (b*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*f) - (Sqrt[e]*(10*a*d*f*(d*e - 2*c*f) - b*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d*(-f)^(5/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(d*e - c*f)*(4*b*d*e - 3*b*c*f - 5*a*d*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*d*(-f)^(5/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)*(c + d*x^2)^(1/2), x, 6, (b*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*f) + (Sqrt[e]*(2*b*d*e - b*c*f - 3*a*d*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*d*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (b*c*Sqrt[e]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*d*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(1/2), x, 5, (b*Sqrt[e]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(d*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)*Sqrt[e]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(3/2), x, 6, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(c*(d*e - c*f)*Sqrt[c + d*x^2])) - ((b*c - a*d)*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*d*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (b*Sqrt[e]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(5/2), x, 7, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(3*c*(d*e - c*f)*(c + d*x^2)^(3/2))) + ((2*a*d*(d*e - 2*c*f) + b*c*(d*e + c*f))*x*Sqrt[e + f*x^2])/(3*c^2*(d*e - c*f)^2*Sqrt[c + d*x^2]) + (Sqrt[e]*Sqrt[-f]*(2*a*d*(d*e - 2*c*f) + b*c*(d*e + c*f))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*d*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + ((b*c - a*d)*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*d*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(1/2)/(c + d*x^2)^(7/2), x, 8, -(((b*c - a*d)*x*Sqrt[e + f*x^2])/(5*c*(d*e - c*f)*(c + d*x^2)^(5/2))) + ((4*a*d*(d*e - 2*c*f) + b*c*(d*e + 3*c*f))*x*Sqrt[e + f*x^2])/(15*c^2*(d*e - c*f)^2*(c + d*x^2)^(3/2)) + ((b*c*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) + a*d*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2))*x*Sqrt[e + f*x^2])/(15*c^3*(d*e - c*f)^3*Sqrt[c + d*x^2]) + (Sqrt[e]*Sqrt[-f]*(b*c*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2) + a*d*(8*d^2*e^2 - 23*c*d*e*f + 23*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^3*d*(d*e - c*f)^3*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*Sqrt[-f]*(4*a*d*(d*e - 2*c*f) + b*c*(d*e + 3*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*c^2*d*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(5/2), x, 8, -(((b*e - a*f)*x*(c + d*x^2)^(5/2))/(e*f*Sqrt[e + f*x^2])) - (d*(b*e*(24*d*e - 23*c*f) - 5*a*f*(4*d*e - 3*c*f))*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*e*f^3) + (d*(6*b*e - 5*a*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*e*f^2) + ((5*a*f*(8*d^2*e^2 - 13*c*d*e*f + 3*c^2*f^2) - 2*b*e*(24*d^2*e^2 - 44*c*d*e*f + 19*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*Sqrt[e]*(-f)^(7/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*(d*e - c*f)*(b*e*(24*d*e - 23*c*f) - 5*a*f*(4*d*e - 3*c*f))*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*Sqrt[e]*(-f)^(7/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(3/2), x, 7, -(((b*e - a*f)*x*(c + d*x^2)^(3/2))/(e*f*Sqrt[e + f*x^2])) + (d*(4*b*e - 3*a*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*e*f^2) - ((b*e*(8*d*e - 7*c*f) - 3*a*f*(2*d*e - c*f))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*Sqrt[e]*(-f)^(5/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*(4*b*e - 3*a*f)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*Sqrt[e]*(-f)^(5/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)*(c + d*x^2)^(1/2), x, 6, -(((b*e - a*f)*x*Sqrt[c + d*x^2])/(e*f*Sqrt[e + f*x^2])) - ((2*b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(Sqrt[e]*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(Sqrt[e]*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(1/2), x, 6, ((b*e - a*f)*x*Sqrt[c + d*x^2])/(e*(d*e - c*f)*Sqrt[e + f*x^2]) - ((b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(Sqrt[e]*Sqrt[-f]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (a*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(3/2), x, 7, -(((b*c - a*d)*x)/(c*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) - (f*(2*b*c*e - a*d*e - a*c*f)*x*Sqrt[c + d*x^2])/(c*e*(d*e - c*f)^2*Sqrt[e + f*x^2]) - (Sqrt[-f]*(2*b*c*e - a*d*e - a*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*Sqrt[e]*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + ((b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(Sqrt[e]*Sqrt[-f]*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(a + b*x^2)/(e + f*x^2)^(3/2)/(c + d*x^2)^(5/2), x, 8, -(((b*c - a*d)*x)/(3*c*(d*e - c*f)*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])) + ((2*a*d*(d*e - 3*c*f) + b*c*(d*e + 3*c*f))*x)/(3*c^2*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (f*(b*c*e*(d*e + 7*c*f) + a*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2))*x*Sqrt[c + d*x^2])/(3*c^2*e*(d*e - c*f)^3*Sqrt[e + f*x^2]) + (Sqrt[-f]*(b*c*e*(d*e + 7*c*f) + a*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2))*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*Sqrt[e]*(d*e - c*f)^3*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[-f]*(4*b*c*e - a*d*e - 3*a*c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*Sqrt[e]*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{(a + b*x^2)/(Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2]), x, 3, (Sqrt[2]*b*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(d*Sqrt[-f]) - ((2*b - a*d)*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(Sqrt[2]*d*Sqrt[-f])}
{(a + b*x^2)*Sqrt[2 + d*x^2]/Sqrt[3 + f*x^2], x, 4, (b*x*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2])/(3*f) + (Sqrt[2]*(6*b*d - 2*b*f - 3*a*d*f)*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(3*d*(-f)^(3/2)) - (Sqrt[2]*b*(3*d - 2*f)*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(3*d*(-f)^(3/2))}
{(a + b*x^2)*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2], x, 5, ((3*b*d - 4*b*f + 5*a*d*f)*x*Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2])/(15*d*f) + (b*x*(2 + d*x^2)^(3/2)*Sqrt[3 + f*x^2])/(5*d) - (Sqrt[2]*(5*a*d*f*(3*d + 2*f) - 2*b*(9*d^2 - 6*d*f + 4*f^2))*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(15*d^2*(-f)^(3/2)) - (Sqrt[2]*(3*d - 2*f)*(3*b*d - 4*b*f + 5*a*d*f)*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(15*d^2*(-f)^(3/2))}


{(b - Sqrt[b^2 - 4*a*c] + 2*c*x^2)/(Sqrt[1 + (2*c*x^2)/(b - Sqrt[b^2 - 4*a*c])]*Sqrt[1 + (2*c*x^2)/(b + Sqrt[b^2 - 4*a*c])]), x, 2, ((b - Sqrt[b^2 - 4*a*c])*Sqrt[b + Sqrt[b^2 - 4*a*c]]*EllipticE[ArcSin[(Sqrt[2]*Sqrt[-c]*x)/Sqrt[b + Sqrt[b^2 - 4*a*c]]], (b + Sqrt[b^2 - 4*a*c])/(b - Sqrt[b^2 - 4*a*c])])/(Sqrt[2]*Sqrt[-c])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (c+d x^2)^(p/2) (e+f x^2)^(q/2) / (a+b x^2)*)


{(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(5/2), x, 32, ((b*c - a*d)^2*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^3) + (2*(b*c - a*d)*(3*d*e - c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b^2) + (d*(9*c*e + (d*e^2)/f - (2*c^2*f)/d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(35*b) + ((b*c - a*d)*f*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*b^2) + (2*(4*d*e - c*f)*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(35*b) + (f*x*(c + d*x^2)^(5/2)*Sqrt[e + f*x^2])/(7*b) + (Sqrt[c]*(b*c - a*d)^3*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^4*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (2*(b*c - a*d)^2*Sqrt[e]*Sqrt[-f]*(2*d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^3*d*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + ((b*c - a*d)*Sqrt[e]*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b^2*d*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (2*Sqrt[e]*(d*e + c*f)*(d^2*e^2 - 6*c*d*e*f + c^2*f^2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(35*b*d*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)^3*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^5*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*Sqrt[e]*(3*d*e - 2*c*f)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^3*d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (2*c*(b*c - a*d)*Sqrt[e]*(d*e - c*f)*(3*d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b^2*d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(d*e - c*f)*(d^2*e^2 + 9*c*d*e*f - 2*c^2*f^2)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(35*b*d*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^3*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^5*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(3/2), x, 23, ((b*c - a*d)*f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) + (2*(3*d*e - c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b) + (f*x*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])/(5*b) + (Sqrt[c]*(b*c - a*d)^2*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^3*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (2*(b*c - a*d)*Sqrt[e]*Sqrt[-f]*(2*d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*d*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(3*d^2*e^2 + 7*c*d*e*f - 2*c^2*f^2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b*d*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)^2*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^4*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + ((b*c - a*d)*Sqrt[e]*(3*d*e - 2*c*f)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (2*c*Sqrt[e]*(d*e - c*f)*(3*d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b*d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^2*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^4*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)*(c + d*x^2)^(1/2), x, 15, (f*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b) + (Sqrt[c]*(b*c - a*d)*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^2*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (2*Sqrt[e]*Sqrt[-f]*(2*d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*d*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^3*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[e]*(3*d*e - 2*c*f)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*d*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^3*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(1/2), x, 8, (Sqrt[c]*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^2*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(3/2), x, 20, (f*x*Sqrt[e + f*x^2])/(b*c*Sqrt[c + d*x^2]) + (d*f*(b*e - a*f)*x*Sqrt[e + f*x^2])/(b^2*c*(d*e - c*f)*Sqrt[c + d*x^2]) - (d^2*(b*e - a*f)^2*x*Sqrt[e + f*x^2])/(b^2*c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]) - (Sqrt[e]*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*c*d*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*(-f)^(3/2)*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*c*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)^2*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*c*(b*c - a*d)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*d*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b*Sqrt[-d]*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(3/2)/(a + b*x^2)/(c + d*x^2)^(5/2), x, 31, (f*x*Sqrt[e + f*x^2])/(3*b*c*(c + d*x^2)^(3/2)) + (d*f*(b*e - a*f)*x*Sqrt[e + f*x^2])/(3*b^2*c*(d*e - c*f)*(c + d*x^2)^(3/2)) - (d^2*(b*e - a*f)^2*x*Sqrt[e + f*x^2])/(3*b^2*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2)) + (2*d*f*(b*e - a*f)*(d*e - 2*c*f)*x*Sqrt[e + f*x^2])/(3*b^2*c^2*(d*e - c*f)^2*Sqrt[c + d*x^2]) - (2*d^2*(b*e - a*f)^2*(d*e - 2*c*f)*x*Sqrt[e + f*x^2])/(3*b^2*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[c + d*x^2]) - (d^2*(b*e - a*f)^2*x*Sqrt[e + f*x^2])/(b*c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]) + (f*(2*d*e - c*f)*x*Sqrt[e + f*x^2])/(3*b*c^2*(d*e - c*f)*Sqrt[c + d*x^2]) - (2*Sqrt[e]*(-f)^(3/2)*(b*e - a*f)*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*c^2*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (2*d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)^2*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)^2*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (Sqrt[e]*(-f)^(3/2)*(2*d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c^2*d*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c*d*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[e]*(-f)^(3/2)*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*c*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*e - a*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(5/2), x, 23, (d*(b*c - a*d)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b^2) - (2*d*(d*e - 3*c*f)*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(15*b*f) + (d^2*x*Sqrt[c + d*x^2]*(e + f*x^2)^(3/2))/(5*b*f) - (Sqrt[c]*Sqrt[-d]*(b*c - a*d)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^3*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + ((b*c - a*d)*Sqrt[e]*(d*e + c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)^3*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^4*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (c*(b*c - a*d)*Sqrt[e]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b^2*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) - (c*Sqrt[e]*(d*e - c*f)*(d*e + 3*c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(15*b*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^3*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^4*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(3/2), x, 15, (d*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b) - (Sqrt[c]*Sqrt[-d]*(b*c - a*d)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^2*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (Sqrt[e]*(d*e + c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - ((b*c - a*d)^2*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^3*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (c*Sqrt[e]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^2*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^3*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)*(c + d*x^2)^(1/2), x, 8, -((Sqrt[c]*Sqrt[-d]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e])) - ((b*c - a*d)*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^2*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(1/2), x, 5, -((Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) + (Sqrt[c]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(3/2), x, 12, (d*f*x*Sqrt[e + f*x^2])/(b*c*(d*e - c*f)*Sqrt[c + d*x^2]) - (d^2*(b*e - a*f)*x*Sqrt[e + f*x^2])/(b*c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]) - (Sqrt[e]*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*c*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*c*(b*c - a*d)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{(e + f*x^2)^(1/2)/(a + b*x^2)/(c + d*x^2)^(5/2), x, 23, (d*f*x*Sqrt[e + f*x^2])/(3*b*c*(d*e - c*f)*(c + d*x^2)^(3/2)) - (d^2*(b*e - a*f)*x*Sqrt[e + f*x^2])/(3*b*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2)) + (2*d*f*(d*e - 2*c*f)*x*Sqrt[e + f*x^2])/(3*b*c^2*(d*e - c*f)^2*Sqrt[c + d*x^2]) - (2*d^2*(b*e - a*f)*(d*e - 2*c*f)*x*Sqrt[e + f*x^2])/(3*b*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[c + d*x^2]) - (d^2*(b*e - a*f)*x*Sqrt[e + f*x^2])/(c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]) - (2*Sqrt[e]*(-f)^(3/2)*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c^2*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (2*d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (Sqrt[e]*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (d*Sqrt[e]*Sqrt[-f]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b*Sqrt[c]*(b*e - a*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(5/2), x, 15, (d^2*x*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])/(3*b*f) + (d*(b*c - a*d)*Sqrt[e]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (2*d*Sqrt[e]*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (d*(b*c - a*d)^2*Sqrt[e]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^3*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) - (c*d*Sqrt[e]*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*b*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^3*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^3*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(3/2), x, 8, (d*Sqrt[e]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (d*(b*c - a*d)*Sqrt[e]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^2*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))*(c + d*x^2)^(1/2), x, 5, (d*Sqrt[e]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(1/2), x, 2, (Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(3/2), x, 7, -((d^2*x*Sqrt[e + f*x^2])/(c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2])) - (d*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*(b*c - a*d)*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (b*Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(1/2))/(c + d*x^2)^(5/2), x, 15, -((d^2*x*Sqrt[e + f*x^2])/(3*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2))) - (2*d^2*(d*e - 2*c*f)*x*Sqrt[e + f*x^2])/(3*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[c + d*x^2]) - (b*d^2*x*Sqrt[e + f*x^2])/(c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]) - (2*d*Sqrt[e]*Sqrt[-f]*(d*e - 2*c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (b*d*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (d*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b^2*Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(5/2), x, 27, (d*(b*c - a*d)*x*Sqrt[c + d*x^2])/(b^2*e*Sqrt[e + f*x^2]) - (d*(b*c - a*d)^2*f*x*Sqrt[c + d*x^2])/(b^3*e*(d*e - c*f)*Sqrt[e + f*x^2]) + ((b*c - a*d)^3*f^2*x*Sqrt[c + d*x^2])/(b^3*e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) - (d*(d*e - c*f)*x*Sqrt[c + d*x^2])/(b*e*f*Sqrt[e + f*x^2]) + (Sqrt[c]*(-d)^(3/2)*(b*c - a*d)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^3*e*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (Sqrt[c]*Sqrt[-d]*(b*c - a*d)^3*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^3*e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (d*(b*c - a*d)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*(2*d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[e]*(-f)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*d*(b*c - a*d)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b^2*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (c*d*(d*e - c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[e]*(-f)^(3/2)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^3*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b^2*Sqrt[-d]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(3/2), x, 20, (d*x*Sqrt[c + d*x^2])/(b*e*Sqrt[e + f*x^2]) - (d*(b*c - a*d)*f*x*Sqrt[c + d*x^2])/(b^2*e*(d*e - c*f)*Sqrt[e + f*x^2]) + ((b*c - a*d)^2*f^2*x*Sqrt[c + d*x^2])/(b^2*e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) + (Sqrt[c]*(-d)^(3/2)*(b*c - a*d)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^2*e*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (Sqrt[c]*Sqrt[-d]*(b*c - a*d)^2*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b^2*e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (d*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[e]*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) + (c*d*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(b*Sqrt[e]*Sqrt[-f]*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (Sqrt[c]*(b*c - a*d)^2*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*b*Sqrt[-d]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))*(c + d*x^2)^(1/2), x, 12, -((d*f*x*Sqrt[c + d*x^2])/(b*e*(d*e - c*f)*Sqrt[e + f*x^2])) + ((b*c - a*d)*f^2*x*Sqrt[c + d*x^2])/(b*e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) + (Sqrt[c]*(-d)^(3/2)*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b*e*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (Sqrt[c]*Sqrt[-d]*(b*c - a*d)*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(b*e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (Sqrt[c]*(b*c - a*d)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(1/2), x, 7, (f^2*x*Sqrt[c + d*x^2])/(e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) + (Sqrt[c]*Sqrt[-d]*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) + (b*Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(3/2), x, 15, -((d^2*x)/(c*(b*c - a*d)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])) + (b*f^2*x*Sqrt[c + d*x^2])/((b*c - a*d)*e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) - (d*f*(d*e + c*f)*x*Sqrt[c + d*x^2])/(c*(b*c - a*d)*e*(d*e - c*f)^2*Sqrt[e + f*x^2]) + (b*Sqrt[c]*Sqrt[-d]*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/((b*c - a*d)*e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (d*Sqrt[-f]*(d*e + c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*(b*c - a*d)*Sqrt[e]*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/((b*c - a*d)*Sqrt[e]*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b^2*Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}
{1/((a + b*x^2)*(e + f*x^2)^(3/2))/(c + d*x^2)^(5/2), x, 24, -((d^2*x)/(3*c*(b*c - a*d)*(d*e - c*f)*(c + d*x^2)^(3/2)*Sqrt[e + f*x^2])) - (2*d^2*(d*e - 3*c*f)*x)/(3*c^2*(b*c - a*d)*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) - (b*d^2*x)/(c*(b*c - a*d)^2*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b^2*f^2*x*Sqrt[c + d*x^2])/((b*c - a*d)^2*e*(b*e - a*f)*(d*e - c*f)*Sqrt[e + f*x^2]) - (b*d*f*(d*e + c*f)*x*Sqrt[c + d*x^2])/(c*(b*c - a*d)^2*e*(d*e - c*f)^2*Sqrt[e + f*x^2]) - (d*f*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2)*x*Sqrt[c + d*x^2])/(3*c^2*(b*c - a*d)*e*(d*e - c*f)^3*Sqrt[e + f*x^2]) + (b^2*Sqrt[c]*Sqrt[-d]*f*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/((b*c - a*d)^2*e*(b*e - a*f)*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]) - (b*d*Sqrt[-f]*(d*e + c*f)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(c*(b*c - a*d)^2*Sqrt[e]*(d*e - c*f)^2*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (d*Sqrt[-f]*(2*d^2*e^2 - 7*c*d*e*f - 3*c^2*f^2)*Sqrt[c + d*x^2]*Sqrt[(e + f*x^2)/e]*EllipticE[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c^2*(b*c - a*d)*Sqrt[e]*(d*e - c*f)^3*Sqrt[(c + d*x^2)/c]*Sqrt[e + f*x^2]) - (b*d*Sqrt[-f]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/((b*c - a*d)^2*Sqrt[e]*(d*e - c*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (d*Sqrt[-f]*(d*e + 3*c*f)*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[e]], (d*e)/(c*f)])/(3*c*(b*c - a*d)*Sqrt[e]*(d*e - c*f)^2*Sqrt[c + d*x^2]*Sqrt[e + f*x^2]) + (b^3*Sqrt[c]*Sqrt[(c + d*x^2)/c]*Sqrt[(e + f*x^2)/e]*EllipticPi[(b*c)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[c]], (c*f)/(d*e)])/(a*Sqrt[-d]*(b*c - a*d)^2*(b*e - a*f)*Sqrt[c + d*x^2]*Sqrt[e + f*x^2])}


{Sqrt[2 + d*x^2]*Sqrt[3 + f*x^2]/(a + b*x^2), x, 5, -((Sqrt[3]*Sqrt[-d]*EllipticE[ArcSin[(Sqrt[-d]*x)/Sqrt[2]], (2*f)/(3*d)])/b) - ((2*b - a*d)*Sqrt[-f]*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(Sqrt[2]*b^2) + ((2*b - a*d)*(3*b - a*f)*EllipticPi[(2*b)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[2]], (2*f)/(3*d)])/(Sqrt[3]*a*b^2*Sqrt[-d])}
{Sqrt[2 + d*x^2]/Sqrt[3 + f*x^2]/(a + b*x^2), x, 3, (d*EllipticF[ArcSin[(Sqrt[-f]*x)/Sqrt[3]], (3*d)/(2*f)])/(Sqrt[2]*b*Sqrt[-f]) + ((2*b - a*d)*EllipticPi[(2*b)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[2]], (2*f)/(3*d)])/(Sqrt[3]*a*b*Sqrt[-d])}
{1/Sqrt[2 + d*x^2]/Sqrt[3 + f*x^2]/(a + b*x^2), x, 1, EllipticPi[(2*b)/(a*d), ArcSin[(Sqrt[-d]*x)/Sqrt[2]], (2*f)/(3*d)]/(Sqrt[3]*a*Sqrt[-d])}


{Sqrt[1 - x^2]/((x^2 - 1)*Sqrt[a + b*x^2]), x, 3, -((Sqrt[(a + b*x^2)/a]*EllipticF[ArcSin[x], -(b/a)])/Sqrt[a + b*x^2])}


(* ::Subsection:: *)
(*Integrands of the form (a+b x^2)^(m/2) (c+d x^2)^(p/2) (e+f x^2)^(q/2)*)


(* ::Section:: *)
(*Integrands of the form (a+b x^n)^m (c+d x^n)^p (e+f x^n)^q*)
